### ISSUE TITLE
JPEGmini plugin

### ISSUE THREAD

**Issue by sindresorhus** [imagemin/imagemin#102]
It's a paid OS X only app, but it has the best result in lossy minifying JPEGs in my experience.

http://www.jpegmini.com/

Inspiration: https://github.com/JamieMason/ImageOptim-CLI/blob/99432e8a2452ba9c58b7355b52c1f063e912caa1/src/imageOptimBashLib#L412-L429

**Comment by kevva** [comment]
How does it compare to mozjpeg?

**Comment by sindresorhus** [comment]
Not sure. The thing about JPEGmini is that it doesn't have any options. It just does a really good lossy minification by default.

**Comment by kevva** [comment]
Using the [images](http://media.jpegmini.com/homepageImages/20131212/zachd1.zip) provided on their website without using any options with mozjpeg.

![2015-06-01 18_12_36-ubuntu running - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/709159/7917327/d94d2432-0889-11e5-9dbc-9196ea9a0354.png)

**Comment by sindresorhus** [comment]
I guess not.
