### ISSUE TITLE
Any way to speed up repeated installations?

### ISSUE THREAD

**Issue by callumlocke** [imagemin/imagemin#107]
I get through lots of small projects that use this module (usually via gulp-imagemin). It takes a huge amount of time running the postinstall scripts for gifsicle, jpegtran and optipng.

Is there any way this could be sped up for repeated installations, avoiding having to compile the binaries every time?

**Comment by shinnn** [comment]
It would speed up each installation:

1. First, install `gulp-imagemin` globally. `npm i -g gulp-imagemin`
2. Then, install `gulp-imagemin` in your project directories *with `--link` flag*. `npm i --link gulp-imagemin`

**Comment by kevva** [comment]
The performance issue is a known one. I'm still trying to find out how to fix it.

**Comment by zanona** [comment]
I often face this problem every time imagine is ran through `npm install` via CI.
It takes about 1'30'' everytime even thought all modules were previously cached and are already installed.
It would be really great if in case the modules were already install once, to simply skip the whole process again. It would make CI builds to run much faster.

**Comment by shinnn** [comment]
@zanona Many CIs support caching.

http://docs.travis-ci.com/user/caching/
https://circleci.com/docs/configuration#cache-directories
http://www.appveyor.com/docs/build-cache

**Comment by zanona** [comment]
Perhaps I wasn't clear enough,
I have caching enabled (using CircleCI here).
But even though, installation takes ages, probably because it has to run installation scripts even though the module is already installed?

**Comment by shinnn** [comment]
1. `npm install` doesn't install already installed modules and doesn't run their `postinstall` scripts.
2. `npm install gulp-imagemin` always installs the latest version regardless whether gulp-imagemin has been installed or not.

**Comment by zanona** [comment]
Just reporting it locally now, hopefully this makes sense:

1 - `imagemin` already installed
2 - run `npm install imagemin` again _(process takes 70s even though it was already installed)_

Why does it takes that long, if it was already installed?

```bash
$ tree -L 2
.
└── node_modules
    └── imagemin

2 directories, 0 files
$ start_time=`date +%s`
$ npm install imagemin && echo run time is $(expr `date +%s` - $start_time) s
\
> jpegtran-bin@3.0.2 postinstall /Users/zanona/Desktop/test/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> gifsicle@3.0.1 postinstall /Users/zanona/Desktop/test/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> optipng-bin@3.0.2 postinstall /Users/zanona/Desktop/test/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
imagemin@3.2.0 node_modules/imagemin
├── get-stdin@4.0.1
├── path-exists@1.0.0
├── optional@0.1.3
├── buffer-to-vinyl@1.0.0 (file-type@2.7.0, uuid@2.0.1, vinyl@0.4.6)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── stream-combiner2@1.0.2 (through2@0.5.1, duplexer2@0.0.2)
├── concat-stream@1.5.0 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.0)
├── meow@3.3.0 (object-assign@3.0.0, minimist@1.1.1, camelcase-keys@1.0.0, indent-string@1.2.1)
├── vinyl-fs@1.0.0 (merge-stream@0.1.7, object-assign@2.1.1, graceful-fs@3.0.8, strip-bom@1.0.0, vinyl@0.4.6, mkdirp@0.5.1, duplexify@3.4.2, glob-stream@4.1.1, glob-watcher@0.0.8)
├── imagemin-svgo@4.1.2 (is-svg@1.1.1, svgo@0.5.2)
├── imagemin-jpegtran@4.2.0 (is-jpg@1.0.0, jpegtran-bin@3.0.2)
├── imagemin-gifsicle@4.2.0 (is-gif@1.0.0, gifsicle@3.0.1)
└── imagemin-optipng@4.3.0 (is-png@1.0.0, exec-buffer@2.0.1, optipng-bin@3.0.2)
run time is 70 s
```

**Comment by shinnn** [comment]
You should use `npm install` for the second installation instead of `npm install imagemin`.

Please, please read at least [previous one comment](https://github.com/imagemin/imagemin/issues/107#issuecomment-113459970).

**Comment by zanona** [comment]
Thanks man, I got it now after, at least, reading and understanding the previous comment.
Apparently CircleCI still re-installing the module even with `npm install` and I am trying to liaise with them to know the cause.

Have a great day
