### ISSUE TITLE
npm --ignore-scripts will fail installation

### ISSUE THREAD

**Issue by k3rmitt** [imagemin/imagemin#108]
Based on this article, I want to be NPM repo free. 

They advice to to store in my repo the result of:
 npm install --ignore-scripts    # Download modules without building them
 git add . && git commit -a      # Check in modules
 npm rebuild                     # Build the modules
 git status                      # Show the files created by the build (there might not be any)

http://www.letscodejavascript.com/v3/blog/2014/03/the_npm_debacle

**Comment by shinnn** [comment]
You don't need to do so. Just run `npm install`.
