### ISSUE TITLE
Error - "no writecb in Transform class"

### ISSUE THREAD

**Issue by timelf123** [imagemin/imagemin#113]
Using the imagemin-cli like so:
`imagemin images/ imagesopt/` where images is a folder with mixed image filetypes.

Running latest imagemin-cli, installed via `npm install imagemin-cli -g`

I've tried wiping my global npm directory and reinstalling imagemin

**Comment by Indee1026** [comment]
I get this same error only with SVG files, the JPG's and PNG's in the folder work just fine.

**Comment by sblaurock** [comment]
Getting something similar within mozjpeg:

[Error: no writecb in Transform class]
Error: no writecb in Transform class
    at afterTransform (../imagemin-mozjpeg/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:95:33)
    at TransformState.afterTransform (../node_modules/imagemin-mozjpeg/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at ChildProcess.<anonymous> (../node_modules/imagemin-mozjpeg/index.js:114:5)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

**Comment by kevva** [comment]
All this errors most likely means that something went wrong during the install.

**Comment by sblaurock** [comment]
@kevva You're right - not meeting the Node / NPM dependency requirements - didn't notice as it is part of an automated build. Thanks!

**Comment by sblaurock** [comment]
@kevva You're right - not meeting the Node / NPM dependency requirements - didn't notice as it is part of an automated build. Thanks!

**Comment by Shinchy** [comment]
I'm getting the same error, but Only on a certain type of SVG. I did a bit of investigating and it appears to be related to the illustrator header added to the SVG, if you remove it, then the compiller will minify the image fine.

**Comment by Indee1026** [comment]
Brilliant, thanks @Shinchy!  Removing the Illustrator headed sorted the problem and the SVG files compile just fine now.

**Comment by frebro** [comment]
Got halted by the same error, and removing the Illustrator header did not help. I did however find that there was an attribute called `sodipodi:nodetypes` on one of the paths, which caused the `Error: no writecb in Transform class´. Removing the attribute solved it for me.

**Comment by shinnn** [comment]
Fixed in https://github.com/imagemin/imagemin-svgo/commit/1f3d87dad7557130c1c87b948f2b51f427e6aa8a
