### ISSUE TITLE
How does imagemin-cli -o work?

### ISSUE THREAD

**Issue by bitinn** [imagemin/imagemin#115]
My command: `imagemin -i -p -o 7 images/* public/images/`

Google PageSpeed keep suggesting my images can be improved by Losslessly Compressing, since I am already using `imagemin`, I thought I should try tuning the optimization level. But whether I set it to `-o 0` or `-o 7` or leave it as default, the result images always seem to have exactly the same bytesize.

Most of my source images are directly from Pixelmator using JPEG at 95% quality, I doubt they are that optimized. Could you explain how does this parameter actually work?

Here an example image for investigation (hopefully github upload doesn't modify it)

![footer-960](https://cloud.githubusercontent.com/assets/1484279/8797967/a5a157ec-2fd1-11e5-8df4-1a5608012d87.jpg)

**Comment by shinnn** [comment]
`-o` affects PNG only.

It should be documented and CLI help should explain it.
