### ISSUE TITLE
Images not compressing

### ISSUE THREAD

**Issue by jacob-israel-turner** [imagemin/imagemin#117]
This is my first time dealing with image compression, but I do have a fair amount of experience with Node and JavaScript.

I'm uploading an image from a client (iPhone), trying to compress it (using imagemin), then uploading it to an S3 bucket.

It all _works_, however, the images are not being altered at all.  I feel like I'm missing or have mis-ordered a simple step in the process.  Here's my code:

``` javascript
new Imagemin()
  .src(req.file.path)
  .dest('uploads/optimized')
  .use(Imagemin.jpegtran({progressive: false}))
  // .use(imageminMozpeg({progressive: true, quality: 40}))
  .run(function(err, files){
    if(err) console.error(err);
    else {
      // S3 upload stuff...
    }
  })
```

I've tried using the builtin `jpegtran` and your [mozpeg](https://github.com/imagemin/imagemin-mozjpeg) plugin, both with the same results.  The image is being saved in `uploads/optimized`, but it's simply the same image as before.

Any help would be appreciated.  Thanks guys!

**Comment by jacob-israel-turner** [comment]
@kevva Any feedback for me?  I'm just trying to figure out if the error is on my side or not.

**Comment by shinnn** [comment]
@jacob-israel-turner 

Please slim down your issue report/code and just check whether the images are minified *locally*. If they are well minified in your local folder but not in S3, it's not an issue with this project but your S3 upload script.

**Comment by jacob-israel-turner** [comment]
@shinnn Thanks for the response.  Sorry, I should have clarified. I've checked the images both on S3 and locally.  It hasn't been altered in either place.

**Comment by shinnn** [comment]
@jacob-israel-turner 

1. Could you show us the slimmed-down script and the image(s) that cannot be minified?
2. Could you show us the result of these commands?

    ```sh
    # in your project directory
    $ node -v
    $ npm -v
    $ npm ls imagemin
    ```

**Comment by jacob-israel-turner** [comment]
I've trimmed out the S3 code from my original post.

[Here](https://s3-us-west-1.amazonaws.com/cancerspot/profile_pictures/-JvFcdDj-aTsvmB5nch0--1438019415290.jpeg) is one of the images I'm trying to compress.  The size of the image locally before compression, locally after compression, and on my S3 bucket is the same.  I even ran a checksum against the two images locally and they are identical.

Node version is 2.3.3 (io.js), NPM is 2.11.3, and imagemin is 3.2.0.

Would this be because I'm using io.js?

**Comment by shinnn** [comment]
> Would this be because I'm using io.js?

I don't think so. Lately I'm using imagemin with io.js, too.

**Comment by jacob-israel-turner** [comment]
Interesting.  It almost feels like I've just got something simple in the wrong order, but no combination that I've tried seems to change anything.

**Comment by shinnn** [comment]
Ah, OK I found the cause. Your image has `.jpeg` extension but actually it's a PNG file.

1. Check your files have correct file extensions and rename them if needed. [`file-type`](https://github.com/sindresorhus/file-type#cli) CLI would help you.
2. Use effective imagemin plugins for those images. `Imagemin.jpegtran` does nothing in this case because the image is PNG.

**Comment by jacob-israel-turner** [comment]
Aah, very interesting.  These are images coming from an iPhone simulator.  I'll play around with it a bit and see what I can figure out.  Thanks!

**Comment by jacob-israel-turner** [comment]
@shinnn I just wanted to confirm, that was the issue.  Super bizarre. Thanks for the help.
