### ISSUE TITLE
image is not compressed 

### ISSUE THREAD

**Issue by johnlim5847** [imagemin/imagemin#120]
everything work fine, no error but my image is not compressed. i'm using it with expressjs multer

here's are my code.

```Javascript
app.use(multer({ dest: './public/images',
                 limits: { fileSize: 6* 1024 * 1024},
                 onFileUploadComplete : function(file) {
                   if(file.extension == 'jpg'){
                     var imagemin = new Imagemin().src(file.path).dest('./public/imagesOptimized').use(Imagemin.jpegtran({progressive: true}));
                      imagemin.run(function(err, files) {
                          if (err) {
                            return next(err);
                          }
                         console.log('Files optimized successfully! JPEG');
                       });
                   }else if(file.extension =='png') {
                     var imagemin = new Imagemin().src(file.path).dest('./public/imagesOptimized').use(Imagemin.optipng({optimizationLevel: 3}));
                      imagemin.run(function(err, files) {
                          if (err) {
                            return next(err);
                          }
                         console.log('Files optimized successfully! PNG ');
                       });
                   }
                   }
                 }
               ));

```
the image is uploaded to `./public/images` and it is not compressed so i added the `.dest()` argument in Imagemin and try to upload compressed image to another folder which is `./public/imagesOptimized` but i got nth in that folder.

**Comment by johnlim5847** [comment]
well,  i can compress JPEG. the bundle plugin `optipng` is not working. i ended up using imageminPngquant

**Comment by shinnn** [comment]
@johnlim5847 What do you mean by "not compressed"? Do they have exactly the same file size?

**Comment by johnlim5847** [comment]
@shinnn  yes all have the same file size when i'm using `optipng`.However, the file size is reduce when using `imageminPngquant `

**Comment by shinnn** [comment]
@johnlim5847 Can you show us one of the PNG images that Imagemin can't optimize at all?

**Comment by johnlim5847** [comment]
@shinnn  i don't think is about the PNG image, it is about the plugin  which is `Imagemin.optipng`. i have tried other PNG plugin it works.

**Comment by shinnn** [comment]
[The test of this project](https://github.com/imagemin/imagemin/tree/master/test) includes PNG optimization and it works.

**Comment by shinnn** [comment]
This issue will never be fixed if you can't provide enough information for us. [Sometimes the image itself would be a root cause](https://github.com/imagemin/imagemin/issues/117#issuecomment-130205431).
