### ISSUE TITLE
Error installing imagemin module

### ISSUE THREAD

**Issue by davidgebbett** [imagemin/imagemin#121]
I get an error when trying to imagemin to any project that has a either a space or a fullstop in the path.

Firstly I get the following error when it comes to a space in the path:
Command failed: 'C:\TFS\Development\Creative' is not recognized as an internal or external command,
operable program or batch file.

Further on I get an error when it comes to a full stop in the path giving me the following error:  
Command failed: '.' is not recognized as an internal or external command,
operable program or batch file.

The error would appear to be with optipng-bin module.

My gulpfile.js file:
var gulp = require('gulp');
var imagemin = require('gulp-imagemin');
var pngquant = require('imagemin-pngquant');

gulp.task('imageOptim', function () {
    return gulp.src('UI/Images/*')
        .pipe(imagemin({
            progressive: true,
            svgoPlugins: [{removeViewBox: false}],
            use: [pngquant()]
        }))
        .pipe(gulp.dest('UI/Images'));
});

gulp.task('default', function() {
    gulp.watch('UI/Images/*',['imageOptim'])
});

I am running this on a Windows 8.1 development machine.

**Comment by shinnn** [comment]
@davidgebbett 

Can you show us the output of:

```
node --version
npm --version
```

**Comment by davidgebbett** [comment]
node --version: v0.10.15
npm --version: v2.7.4

**Comment by shinnn** [comment]
> node --version: v0.10.15

You're using an ancient version of Node. Regardless of this issue I strongly recommend to use the latest Node.

**Comment by shinnn** [comment]
@davidgebbett Can you try `npm install imagemin` after upgrading `node`?

**Comment by davidgebbett** [comment]
I have upgraded node to v. 0.12.7 It would appear to have fixed the problem, Thanks for your help

**Comment by shinnn** [comment]
@davidgebbett Glad to hear that.

Closing this issue since we should not spent a lot of time for tackling problems cause by Node 0.x. Node v4.0, which is actually v1.0, is coming soon. https://medium.com/node-js-javascript/4-0-is-the-new-1-0-386597a3436d
