### ISSUE TITLE
CLI Jpg's not compressing

### ISSUE THREAD

**Issue by roikles** [imagemin/imagemin#122]
Running the following from the command line compresses any pngs perfectly but it seems to ignore any jpg images and fails silently using the following command:

`imagemin assets/imgs build/assets/imgs`

I can confirm that the images are copied over to the destination folder but It appears that jpegtrans is failing silently as the images are identical in file size. 

For testing purposes I cropped a photo down to 1000x500 and saved it out in photoshop with the maximum filesize settings. Then I placed it in the source folder as mentioned above.

Any help would be appreciated, Im sure that it is something that I have done wrong as nobody seems to be having the same issue :)

**Comment by jedrichards** [comment]
I think I see something similar. With default options I was seeing no change in JPG file sizes. Adding the `--progressive` seemed to do something though. Not sure if this is expected behaviour?

**Comment by gbabula** [comment]
I don't see any JPG compression even with the --progressive flag.

**Comment by visualcookie** [comment]
Having the same issue there. JPGs won't compress properly.

**Comment by shinnn** [comment]
@roikles @jedrichards @gbabula @visualcookie Could you show us one of the images causing a problem?

**Comment by gbabula** [comment]
@shinnn

Previously, I was able to reproduce this with every image I tried (~20 attempts).

Ran a few tests now and it appears most images are reporting savings.

Not sure if there was an update in the past week,
 but something appears to have changed for the better :+1: 

---

__Image__
https://upload.wikimedia.org/wikipedia/commons/a/a0/Jaws_Beach.jpg

__Input__
1.3MB

__Output__
1.1MB

---

__Image__
https://upload.wikimedia.org/wikipedia/commons/3/3e/Teddies_in_Space.jpg

__Input__
894KB

__Output__
808KB

**Comment by shinnn** [comment]
@gbabula Thanks for reporting.

@roikles @jedrichards @visualcookie What else?

**Comment by visualcookie** [comment]
Well I changed from ```jpegoptim``` to ```mozjpeg```. Seems to work.

**Comment by davimba** [comment]
same issue here , i'm using imagemin-cli and the size of output file is the same.

**Comment by shinnn** [comment]
@davimba https://github.com/imagemin/imagemin/issues/122#issuecomment-142893012

**Comment by davimba** [comment]
http://imgur.com/TD8q4hu 
original size -> 984.3k
output size -> 984.3k


<code>$ imagemin -p 1.png media/ </code>
<code>$ imagemin 1.png media/ 
</code>

same result, thanks in advance.

**Comment by shinnn** [comment]
@davimba Read the issue title befor submitting new comments.

> CLI **Jpg**'s not compressing

I directly optimized your image with optipng. here is the result.

```
$ optipng --version
OptiPNG version 0.7.5
Copyright (C) 2001-2014 Cosmin Truta and the Contributing Authors.

This program is open-source software. See LICENSE for more details.

Portions of this software are based in part on the work of:
  Jean-loup Gailly and Mark Adler (zlib)
  Glenn Randers-Pehrson and the PNG Development Group (libpng)
  Miyasaka Masaru (BMP support)
  David Koblas (GIF support)

Using libpng version 1.6.10-optipng and zlib version 1.2.5
$ optipng *.png
** Processing: TD8q4hu .png
960x720 pixels, 3x8 bits/pixel, RGB
Input IDAT size = 983864 bytes
Input file size = 984308 bytes

Trying:
                               
TD8q4hu .png is already optimized.
```

That's not a imagemin-related issue.

**Comment by shinnn** [comment]
Closing this issue for no enough feedback on https://github.com/imagemin/imagemin/issues/122#issuecomment-143284994.
