### ISSUE TITLE
Animated gif

### ISSUE THREAD

**Issue by bampakoa** [imagemin/imagemin#123]
Hi,

I am using imagemin as a plugin with gulp and tried to compress an animated gif but it failed. Does it support the particular format?

Thanks

**Comment by shinnn** [comment]
This should discussed in https://github.com/kohler/gifsicle/issues rather than here.

**Comment by bampakoa** [comment]
@shinnn Thanks for your help. Finding the correct responsible repo for reporting it, was really confusing.
