### ISSUE TITLE
Can't use `imagemin images/* build` without TTY

### ISSUE THREAD

**Issue by lalinsky** [imagemin/imagemin#124]
It seems that the output behavior changes whether I'm running `imagemin` with a TTY or not. I'm running this in an Ansible playbook, which is connecting to a server remotely and it doesn't have a TTY. I'd still like to be able to generate the files in a directory, not print them to stdout.

Can you please add an option to disable this behavior? Or maybe even remove the custom behavior for non-TTY terminals. I don't know the use case, but it surprised me to find it there.

**Comment by kevva** [comment]
This should work now https://github.com/imagemin/imagemin-cli/blob/master/cli.js#L132. We aren't checking for `TTY`, only for the input length.
