### ISSUE TITLE
Error installing imagemin module with spaces in the directory

### ISSUE THREAD

**Issue by jdtaylor91** [imagemin/imagemin#126]
I get an error when adding imagemin to my project, it seems to be related to a space in the path which causes the 'optipng-bin' dependency to error.

When i run 'npm install gulp-imagemin' the following error is thrown:

```
  ‼ Command failed: C:\Windows\system32\cmd.exe /s /c "C:\Projects\My Project\Staging\src\Web\node_modules\gulp-imagemin\node_modules\imagemin\node
_modules\imagemin-optipng\node_modules\optipng-bin\vendor\optipng.exe --version"

'C:\Projects\My' is not recognized as an internal or external command,
operable program or batch file.
```

For reference, my node and npm versions are:
```
node --version: v4.1.1
npm --version: v2.14.4
```

I'm not sure if this is something that you are able to fix as it seems related to the 'optipng-bin' package but I wanted to make you aware of this incase you weren't already.

**Comment by honkevin** [comment]
same here

**Comment by shinnn** [comment]
Confirmed. No need to submit confirmation comments any more.

**Comment by shinnn** [comment]
This discussion continues in more proper place: https://github.com/imagemin/optipng-bin/issues/45

Thanks for the clear and detailed report, @jdtaylor91.
