### ISSUE TITLE
encoding images client-side

### ISSUE THREAD

**Issue by avalanche1** [imagemin/imagemin#130]
Hi!
Is it possible to run this lib clientside? Namely, I would like to minify images before uploading them and my current solution uses `canvas.toDataURL`, but it doesn't support progressive jpegs(

**Comment by shinnn** [comment]
> Is it possible to run this lib clientside?

Currently no, and we don't have any plans for supporting client-side usage. imagemin uses some [binaries](https://github.com/imagemin/jpegtran-bin/tree/master/vendor) and (of course) they don't work on browser.

Perhaps [emscripten](https://github.com/kripken/emscripten) helps imagemin to support clent-side.
