### ISSUE TITLE
Image libraries are no longer optional in v3.2.1

### ISSUE THREAD

**Issue by jnicholl** [imagemin/imagemin#131]
In my project, we only use imagemin-optipng since we don't have any jpg/gif/svg files. With version 3.2.1, imagemin no longer runs. The error shown is:
"Fatal error: Cannot read property 'read' of undefined"

The problem appears to be https://github.com/imagemin/imagemin/blob/a2330f418d5e021650aa2d4b992be1a41877be3b/index.js#L134, because the newly constructed PassThrough object is not returned.

Adding "return " at the start of this line fixes the issue.

**Comment by shinnn** [comment]
Confirmed. I'll fix it soon.

**Comment by dsebastien** [comment]
Same issue for me

**Comment by shinnn** [comment]
Fixed in v3.2.2.
