### ISSUE TITLE
Error with images .gif

### ISSUE THREAD

**Issue by gabrielgomesferraz** [imagemin/imagemin#133]
When there is a .gif file in the directory where it has imagemin task the following error occurs:

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /var/www/front-end-boilerplate/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

**Comment by shinnn** [comment]
@gabrielgomesferraz

1. Does the binary `/var/www/front-end-boilerplate/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle` exist?
2. Can you show us the log of `npm install gulp-imagemin`?

**Comment by gabrielgomesferraz** [comment]
The error occurs at the time of the project build and not when installing the gulp-imagemin, sorry for not specify.

**Comment by shinnn** [comment]
OK. then,

> Does the binary `/var/www/front-end-boilerplate/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle` exist?

**Comment by gabrielgomesferraz** [comment]
For other image formats the gulp-imagemin works perfectly, I wonder why only the .gif format it causes this error could please help me?

**Comment by shinnn** [comment]
1. Which OS?
2. Node version?
3. npm version?
4. Could you create a small repository by which we can reproduce the problem?

**Comment by gabrielgomesferraz** [comment]
1. I am using ubunto
2. Node version : v4.0.0
3. npm version: 2.14.2
4. I will create the repository aqui.

**Comment by shinnn** [comment]
> I am using ubunto

32bit or 64bit?

**Comment by gabrielgomesferraz** [comment]
64bit

**Comment by shinnn** [comment]
Can you download [this `gifsicle` binary](https://github.com/imagemin/gifsicle-bin/blob/423db258ace661ea43d001b037a14cd8a02a8aa6/vendor/linux/x64/gifsicle) and check whether it works properly or not?

```
$ gifsicle --version
$ cat your-image.gif | gifsicle -w
```

**Comment by gabrielgomesferraz** [comment]
$ gifsicle --version 

This result:
LCDF Gifsicle 1.78
Copyright (C) 1997-2013 Eddie Kohler
This is free software; see the source for copying conditions.
There is NO warranty, not even for merchantability or fitness for a
particular purpose.

$ cat my.gif  | gifsicle -w

This result:
gifsicle: <stdout>: is a terminal

**Comment by shinnn** [comment]
Then,

```
$ cat my.gif | gifsicle -w > out.gif
```

And, still a small repo would be most helpful.

**Comment by llaski** [comment]
+1 having the same issue

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /Users/larrylaski/Sites/bond/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

**Comment by gabrielgomesferraz** [comment]
I created the repository
https://github.com/gabrielgomesferraz/gulp-imagemin-demo

**Comment by shinnn** [comment]
Add `return` to this line. https://github.com/gabrielgomesferraz/gulp-imagemin-demo/blob/3c552c31b791f8a60ecb272b5de531b614003454/gulpfile.babel.js#L22

```js
return gulp.src('app/assets/images/**')
```

**Comment by gabrielgomesferraz** [comment]
Added the return gulp.src('app/assets/images/**') and continues with the same error.

**Comment by shinnn** [comment]
Not fixed yet. https://github.com/gabrielgomesferraz/gulp-imagemin-demo/blob/3c552c31b791f8a60ecb272b5de531b614003454/gulpfile.babel.js#L22

**Comment by gabrielgomesferraz** [comment]
Sorry, now I added in https://github.com/gabrielgomesferraz/gulp-imagemin-demo/blob/master/gulpfile.babel.js

**Comment by gabrielgomesferraz** [comment]
My friend @diegorodriguesvieira informed me that from version 5.0.0 of the node this error no longer occurs, and I tested with version 5.0.0 of node and is now correctly running .Thanks @shinnn for your help in trying to solve the problem.

**Comment by diegorodriguesvieira** [comment]
:thumbsup:

**Comment by shinnn** [comment]
@diegorodriguesvieira @gabrielgomesferraz :tada: 

I still want to find the root cause, but at least it's not an issue with imagemin, but with Node itself. 

Thanks for the investigation! Really helpful :)
