### ISSUE TITLE
CPU takeover

### ISSUE THREAD

**Issue by ajwhite** [imagemin/imagemin#134]
I noticed when processing a handful of images with imagemin that my CPU became fully utilized

![screen shot 2015-10-24 at 2 36 40 pm](https://cloud.githubusercontent.com/assets/656630/10712080/dc809f4a-7a5c-11e5-82ab-ec624d9a3fc0.png)
![screen shot 2015-10-24 at 2 36 50 pm](https://cloud.githubusercontent.com/assets/656630/10712081/dc8187de-7a5c-11e5-97e6-418a3c48e203.png)

This was while running https://github.com/sindresorhus/gulp-imagemin

I'm wondering if there's anyway that it can utilize resources differently

**Comment by shinnn** [comment]
Cannot reproduce even if I optimize over 250 PNG files with gulp-imagemin.

**Comment by ajwhite** [comment]
Darn. I get this each time. I have a handful of large pngs in there. The build step takes  a good 15 seconds:

This is my configuration
```js
gulp.task('images', function () {
  gulp.src(path.join(paths.source, '_assets/images/**/*'))
  .pipe(imagemin({
    progressive: true,
    svgoPlugins: [{removeViewBox: false}],
    use: [pngquant()]
  }))
  .pipe(gulp.dest(path.join(paths.dist, 'images')));
});
```

And here's the profile, which takes a huge hit:
![screen shot 2015-10-24 at 3 20 00 pm](https://cloud.githubusercontent.com/assets/656630/10712250/ce150602-7a62-11e5-9311-7ff231ed375a.png)

**Comment by ajwhite** [comment]
Running `du` in the images directory yields `18M`, which isn't outstanding

**Comment by shinnn** [comment]
Your gulp task has something wrong. Check the documentation. https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulptaskname-deps-fn

Also seems to be an issue with [optipng](http://sourceforge.net/projects/optipng/) or your images. (In my experience broken image data often causes a lot of unexpected behaviors.)

**Comment by ajwhite** [comment]
Hrmm, I'm a little unclear what would be wrong with the _task_ itself. I've reduced it to:

```js
gulp.task('images', function () {
  gulp.src('src/assets/images/**/*')
  .pipe(imagemin()) // no special options
  .pipe(gulp.dest('public/assets/images'))
});
```

And i still get the same behavior:
![screen shot 2015-10-24 at 3 48 05 pm](https://cloud.githubusercontent.com/assets/656630/10712352/a61e6c20-7a66-11e5-97c6-254899bf76e1.png)


![screen shot 2015-10-24 at 3 48 22 pm](https://cloud.githubusercontent.com/assets/656630/10712357/ad715654-7a66-11e5-9825-9cf1ed2d9291.png)
