### ISSUE TITLE
Error with gulp-imagemin

### ISSUE THREAD

**Issue by zwhitchcox** [imagemin/imagemin#135]
My error: 

```shell
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/zane/narkjs/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

My code: 

```js
 35 gulp.task('images', ['clean'], function() {
 36   return gulp.src(paths.images)
 37     .pipe(imagemin({optimizationLevel:5}))
 38     .pipe(debug())         
 39     .pipe(gulp.dest('build'))
 40 })

```

I was told to report this error to you

**Comment by shinnn** [comment]
https://github.com/sindresorhus/gulp-imagemin/issues/125#issuecomment-149851999

> Should be reported to https://github.com/imagemin/imagemin/issues 
> # in detail

Answer these question.

* https://github.com/imagemin/imagemin/issues/133#issuecomment-149858701
* https://github.com/imagemin/imagemin/issues/133#issuecomment-149866363
* https://github.com/imagemin/imagemin/issues/133#issuecomment-149870088

**Comment by zwhitchcox** [comment]
I think I ran out of memory while installing
