### ISSUE TITLE
'.src(buffer)' image filename is a random number

### ISSUE THREAD

**Issue by markqin** [imagemin/imagemin#136]
When I use 
```javascript
.src(buffer)
```
 I got optimized images success, but these images filename looks like some random number, e.g.
`
 "5d720201-1e25-4e35-b84c-da5b6ad82c18.png" 
`

How to change the filename? I can't use that 'gulp-rename' plugin because my project is not based on gulp.

Thansk!!!

**Comment by shinnn** [comment]
You can create your own renamer plugin with [`through2.ctor`](https://github.com/rvagg/through2/blob/48412d11ee597e909130d18705c60a61a0677fc1/through2.js#L64-L84).

```js
'use strict';

const Imagemin = require('imagemin');
const through2 = require('through2');

new Imagemin()
	.src('test.jpg')
	.dest('./')
	.use(Imagemin.jpegtran({progressive: true}))
	.use(through2.ctor({objectMode: true}, (file, enc, cb) => {
		file.path = 'new_file_path.jpg';
		cb(null, file);
	}))
	.run((err, files) => {
		// ...
	});
```

**Comment by petrck** [comment]
Hi, I try to do something like, in your previous post, but it  doesn't work. Console log inside through2 is not probably called.

```
const through2 = require("through2"); //2.0.3
const imagemin = require('imagemin'); //5.3.1
const imageminJpegtran = require('imagemin-jpegtran'); //5.0.2
const imageminPngquant = require('imagemin-pngquant'); 5.1.0

var myUniqueImages = [...];

imagemin(myUniqueImages, 'img/minified', {
        use: [
            imageminJpegtran({progressive: true}),
            imageminPngquant({quality: '65-80'}),
            through2.ctor(function(file, enc, cb) {
                console.log("Im here...");
                cb(null, file);
            }),            
        ]
    }).then(data => { ... })
```
Console will not write anything, but images are minified without any problem.
Where is problem please? Thank you.
