### ISSUE TITLE
WHY It just stop when install gulp-imagemin

### ISSUE THREAD

**Issue by Loyalsoldier** [imagemin/imagemin#137]
![_20151124114930](https://cloud.githubusercontent.com/assets/10487845/11357558/5d9e0334-92a3-11e5-8517-63fa8f4e0134.png)

The CPU usage is lower than 5%, I'm sure that it just stopped.

Node: v5.1.0
npm: with node
64bit, 4G Memory with 500MB left when installing gulp-imagemin

**Comment by shinnn** [comment]
We don't support cnpm. Just use npm.

**Comment by Loyalsoldier** [comment]
The same problem on npm.

**Comment by shinnn** [comment]
@Loyalsoldier Does your network is behind proxy? And, any environment variable for proxy (e.g. `HTTPS_PROXY`) is enabled?

**Comment by Loyalsoldier** [comment]
@shinnn 
Yep. I use a proxy.
So unlucky in China...
It seems that `cnpm` is our only choice. Hope that imagemin can support cnpm.
