### ISSUE TITLE
node modules install failed

### ISSUE THREAD

**Issue by longge-0516** [imagemin/imagemin#139]
optipng-bin@3.0.3 postinstall D:\projectCode\code\Git\Lizard\imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin
> node lib/install.js
  ‼ read ECONNRESET
  ‼ optipng pre-build test failed
  i compiling from source
  × Error: ./configure --with-system-zlib --prefix="D:\projectCode\code\Git\Lizard\imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor" --bindir="D:\projectCode\code\Git\Lizard\imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor" && make install
Command failed: C:\Windows\system32\cmd.exe /s /c "./configure --with-system-zlib --prefix="D:\projectCode\code\Git\Lizard\imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor" --bindir="D:\projectCode\code\Git\Lizard\imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor""

HOW TO SOLVE THIS????

**Comment by shinnn** [comment]
Will be fixed if @mikeal, the author of [tunnel-agent](https://github.com/mikeal/tunnel-agent), merges https://github.com/mikeal/tunnel-agent/pull/15.

**Comment by longge-0516** [comment]
new BinBuild()
  .src('lib/optipng-0.7.5.tar.gz')
  .cmd([
    './configure --with-system-zlib --prefix=' + "../vendor" + '',
    '--bindir=' + "../vendor" + ''
  ].join(' '))
  .cmd('make install')
  .run(function (err) {
    if (err) {
      log.error(err.stack);
      return;
    }

    log.success('optipng built successfully');
  });

I have download this file and run the up code ,it still comes out that error.

**Comment by shinnn** [comment]
> it still comes out that error.

Of course. Because `BinBuild` is not defined in your code.

**Comment by longge-0516** [comment]
BinBuild is defined   v
ar BinBuild = require('bin-build');
var log = require('logalot');
var bin = require('./');
I didn't paste it, can BinBuild loaded a local file?
I have down this file and unzip it,then run the commond that followed:
$ ./configure --prefix="D:\projectCode\code\Git\Lizard\imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\
optipng-bin\vendor" --bindir="D:\projectCode\code\Git\Lizard\imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin
\vendor"

it came out:
Checking for gcc...
Using pre-configured libpng...
Using pre-configured zlib...
sed: -e expression #1, char 304: unterminated `s' command
sed: -e expression #1, char 304: unterminated `s' command
sed: -e expression #1, char 304: unterminated `s' command
sed: -e expression #1, char 304: unterminated `s' command
sed: -e expression #1, char 304: unterminated `s' command
sed: -e expression #1, char 304: unterminated `s' command
sed: -e expression #1, char 304: unterminated `s' command
sed: -e expression #1, char 304: unterminated `s' command
sed: -e expression #1, char 304: unterminated `s' command
 Then I don't konw how to solve it

**Comment by shinnn** [comment]
Use [Github markdown](https://help.github.com/articles/github-flavored-markdown/) [syntax highlighting](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting). It's hard to determine which part is a code block or not in your comment.

**Comment by longge-0516** [comment]
Can this problem be solved?

**Comment by shinnn** [comment]
> Can this problem be solved?

https://github.com/imagemin/imagemin/issues/139#issuecomment-160619043
