### ISSUE TITLE
Couldn't get imagemin up and running as per the instruction

### ISSUE THREAD

**Issue by vuquangchien** [imagemin/imagemin#140]
I'm trying to get imagemin work in my development machine (windows 10 and cloud.io) but always the the errors:
```
<File "Pomegranate.jpg" <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 02 00 00 64 00 64 00 00 ff db 00 43 00 06 04 04 04 05 04 06 05 05 06 09 06 05 06 09 0b 08 06 06 08 0b 0c 0a 0a 0b ... >>
```
Could you please advise? I've upload the source code here https://github.com/vuquangchien/test-image-min
This is what I've done:
1 - Create a new folder and run ```npm init```
2 - Install imagemin ```npm install imagemin --save```
3 - Create a index.js file with the follow content.
```
const Imagemin = require('imagemin');

new Imagemin()
    .src('images/*.{gif,jpg,png,svg}')
    .dest('build/images')
    .use(Imagemin.jpegtran({progressive: true}))
    .run((err, files) => {
        console.log(files[0]);
        //=> {path: 'build/images/foo.jpg', contents: <Buffer 89 50 4e ...>}
    });
```
also create ```images``` folder and drop some image inside (```Pomegranate.jpg```)
4 - Run ```node index.js```
And I always receive the error above, despite windows or linux (cloud9.io) environment.

**Comment by shinnn** [comment]
> ```
> <File "Pomegranate.jpg" <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 02 00 00 64 00 64 00 00 ff db 00 43 00 06 04 04 04 05 04 06 05 05 06 09 06 05 06 09 0b 08 06 06 08 0b 0c 0a 0a 0b ... >>
> ```

This is not an error message. Read the official Node document. https://nodejs.org/api/console.html#console_console_log_data
