### ISSUE TITLE
Minimum filesize for use of progressive

### ISSUE THREAD

**Issue by AndreasHeiberg** [imagemin/imagemin#142]
I'm trying to get a 100 PageSpeed score, just because :)

Google does not like using progressive on jpg's smaller than ~10KB ([read](http://yuiblog.com/blog/2008/12/05/imageopt-4/))

So I'm being told to compress my images. If I take off progressive my score goes up, but I know that my file sizes are bigger for large images and that the UX is worse.

So ideally I would just want to set progressive_min_size: 10 and only have images larger than that be optimized with progressive enabled.

Tried to find a way of doing this my self, but couldn't really find an easy solution.

Thanks for all the hard work on imagemin :)

**Comment by corps** [comment]
Why not make a first pass through your file globs and filter them into those < and > the 10Kb limit, then pass those two separate file lists into imagemin with different option sets?  Only requires using simple general tools rather than more customizations to a very specific tool.

**Comment by shinnn** [comment]
What @corps said.

**Comment by shinnn** [comment]
@corps Thanks for your detailed answer.
