### ISSUE TITLE
"gulp-imagemin",   "version": "2.4.0", npm WARN cannot run in wd gifsicle@3.0.3 node lib/install.js

### ISSUE THREAD

**Issue by FriendOfFatBeagle** [imagemin/imagemin#143]
I am using: "name": "gulp-imagemin",   "version": "2.4.0",
nodejs = 4.2.4 @ linux.
When I installed like so, I got a warning:
$ sudo npm install gulp-imagemin --save-dev
...... ... ... 
  ✔ jpegtran pre-build test passed successfully
npm WARN cannot run in wd gifsicle@3.0.3 node lib/install.js (wd=/myApp/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle)

Here is a problem: 
gifsicle@3.0.3 is in imagemin-gifsicle@4.2.0
 package
 $ npm ls | grep gifsicle
│ │ ├─┬ imagemin-gifsicle@4.2.0
│ │ │ ├─┬ gifsicle@3.0.3

So when I ran gulp task like so in gulpfile.js:
    del = require('del');
    imagemin = require('gulp-imagemin') 

// Images
gulp.task('imagemin', function() {
  return del(['dist/images']), gulp.src('app/images/**/*')
    .pipe(cache(imagemin({ optimizationLevel: 3, progressive: true, interlaced: true })))
    .pipe(gulp.dest('dist/images'))
    .pipe(notify({ message: 'Images task complete' }));
});

imagemin does not work meaning I do not get any output in dist/images folder and no 
message, 'Images task complete'.

gifsicle@3.0.3 is installed by grulp-imagemin.
What does "npm WARN cannot run in wd gifsicle@3.0.3 node lib/install.js" really mean?
How do I fix this problem?
Thank you.

**Comment by shinnn** [comment]
This is a [gifsicle-bin](https://github.com/imagemin/gifsicle-bin) issue. Also don't run `npm install` with `sudo`.

**Comment by FriendOfFatBeagle** [comment]
Thank you  Shinnosuke.

>>>  Also don't run npm install with sudo.
If I do not run with sudo, it give me error.
I am using Ubuntu.
How do I install without sudo?
Thanks.
