### ISSUE TITLE
access output as buffer/stream?

### ISSUE THREAD

**Issue by jasonswearingen** [imagemin/imagemin#145]
I create images dynamically and send them to the user, and thus want to read/write to a buffer/stream.  is this possible with imagemin?

**Comment by shinnn** [comment]
Yes :+1: https://github.com/imagemin/imagemin#srcfile

**Comment by jasonswearingen** [comment]
@shinnn That is passing the input as a buffer (or am I confused?).  Is there a way to obtain the ***output*** as a buffer/stream?

**Comment by jasonswearingen** [comment]
maybe is it like this?  (sorry I haven't used vinyl before)

```
new Imagemin()
    .use(Imagemin.optipng({optimizationLevel: 3}));
    .src(inputStream)
    .run(function(err,files){
            for(var i=0;i<files.length;i++){
                       var outputStream = new stream.Readable();
                       file.pipe(outputStream);
                       //do something with the outputStream here
           }
       })
 
```
