### ISSUE TITLE
run() does not return data (vinyl-fs 2.3.0 problem)

### ISSUE THREAD

**Issue by benurb** [imagemin/imagemin#147]
Hello there :smile: 

by using grunt-contrib-imagemin I found out there is a problem with the current imagemin, that is caused by an incompatibility between stream-combiner2 1.1.1 and vinyl-fs 2.3.0 (which was released yesterday). The new vinyl-fs version removes the ability to apply `readable` events to the dest stream, but stream-combiner2 relies on this event.

I created a PR for vinyl-fs (https://github.com/gulpjs/vinyl-fs/pull/142), but maybe it's a temporary solution to pin vinyl-fs to 2.2.x in `imagemin`.

What do you think about it? Fact is, that imagemin 4 is broken at the moment, if you rely on the `data` argument of the `run()` callback. Because of the aforementioned incompatibility it's always empty.

Thanks
Ben

**Comment by wardpeet** [comment]
I added "vinyl-fs": "2.2.0" to my package.json removed node_modules and reinstalled all modules and seems to work. Thanks!

**Comment by SpikeShape** [comment]
As a temporary solution I added vinyl-fs to my project's package.json to avoid crashes when running the grunt task.
A bugfix would be greatly appreciated.

**Comment by giamma13** [comment]
+1

**Comment by Fridus** [comment]
+1

**Comment by anbestephen** [comment]
+1

**Comment by sisu4u** [comment]
+1

**Comment by henricavalcante** [comment]
Worked for me. "I added "vinyl-fs": "2.2.0" to my package.json removed node_modules and reinstalled all modules and seems to work. Thanks!" @wardpeet

**Comment by shinnn** [comment]
@giamma13 @Fridus @anbestephen @sisu4u Removed your meaningless +1 comments.

**Comment by shinnn** [comment]
Fixed in https://github.com/gulpjs/vinyl-fs/pull/145.

Thanks for the report, @benurb.
