### ISSUE TITLE
vinyl-fs fixed

### ISSUE THREAD

**Issue by phated** [imagemin/imagemin#148]
I believe you should be able to close #147 as I just released version 2.3.1 of vinyl-fs that fixes the regression introduced in 2.3.0.  Sorry about letting that slip through.

**Comment by shinnn** [comment]
Thanks, @phated and other gulp dev members.

I unlocked https://github.com/imagemin/imagemin/issues/147 and will close it after I confirmed the problem is fixed.

> Sorry about letting that slip through.

No problem. Shit happens.
