### ISSUE TITLE
Crash on Xubuntu 14.04

### ISSUE THREAD

**Issue by Litarvan** [imagemin/imagemin#149]
I've got this :

[20:11:46] Starting 'minimize-images'...

events.js:72
throw er; // Unhandled 'error' event
^
Error: spawn ENOENT
at errnoException (child_process.js:988:11)
at Process.ChildProcess._handle.onexit (child_process.js:779:34)

With this code :

return gulp.src(IMAGES_FOLDER + '/*/.png')
.pipe(imagemin())
.pipe(gulp.dest(MINIMIZED_IMAGES_FOLDER));

If you could help me, thanks by advance

**Comment by mike3run** [comment]
Same here on Ubuntu :cry:

**Comment by shinnn** [comment]
@Litarvan @mike3run 

Can you show us the result of these commands?

```
node -v
npm -v
npm ls imagemin
```

**Comment by Litarvan** [comment]
litarvan@xubuntu-litarvan:~/Documents/Projets/Canvas$ node -v
v0.10.25
litarvan@xubuntu-litarvan:~/Documents/Projets/Canvas$ npm -v
1.3.10
litarvan@xubuntu-litarvan:~/Documents/Projets/Canvas$ npm ls imagemin
npm WARN unmet dependency /home/litarvan/Documents/Projets/Canvas/node_modules/gulp-composer requires gulp-util@'latest' but will load
npm WARN unmet dependency /home/litarvan/Documents/Projets/Canvas/node_modules/gulp-util,
npm WARN unmet dependency which is version 3.0.7
Canvas@1.0.0-BETA /home/litarvan/Documents/Projets/Canvas
└─┬ gulp-imagemin@2.4.0
  └── imagemin@4.0.0 

litarvan@xubuntu-litarvan:~/Documents/Projets/Canvas$

**Comment by shinnn** [comment]
@Litarvan You're using incredibly older Node and npm. Can you upgrade them and try again?

**Comment by Litarvan** [comment]
OH ok, i installed them using apt-get (Xubuntu 14.04) I'll try

**Comment by erwstout** [comment]
I have something similar on Ubuntu 14.04

```
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:367:9)
    at exports.execFile (child_process.js:139:15)
    at ExecBuffer.<anonymous> (/media/ericstout/Storage/git/prelude-test/node_modules/exec-buffer/index.js:91:3)
    at /media/ericstout/Storage/git/prelude-test/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
```

`node -v` = `v5.7.1`
`npm -v` = `3.8.1`

`npm ls imagemin` : 

```
prelude-test@1.0.0 /media/ericstout/Storage/git/prelude-test
└─┬ prelude-wp@3.1.2
  └─┬ gulp-imagemin@2.4.0
    └── imagemin@4.0.0 
```

**Comment by shinnn** [comment]
The issue author said ["I'll try"](https://github.com/imagemin/imagemin/issues/149#issuecomment-182834528) but there is no feedback almost a year. Closing.

@erwstout `EACCES` error is a totally different issue. Open a new issue about it if you still running into the problem.

**Comment by Litarvan** [comment]
Yeah sorry, updating it fixed it

**Comment by shinnn** [comment]
@Litarvan No problem. Glad to hear that the problem was fixed.
