### ISSUE TITLE
Optipng -strip all option

### ISSUE THREAD

**Issue by pietrovismara** [imagemin/imagemin#155]
I see that optipng supports the `-strip all` option to remove metadata from the image. Does Imagemin supports it? And if so, what is the option name? 
I tried with `.use(Imagemin.optipng({optimizationLevel: 3, strip: 'all'}))` but with no results.

If it's not supported, do you plan to implement it anytime soon?

**EDIT**
Looking at imagemin-optipng/index.js i see this:
```
var args = ['-strip', 'all', '-clobber', '-force', '-fix'];
var optimizationLevel = opts.optimizationLevel || 2;

if (typeof optimizationLevel === 'number') {
	args.push('-o', optimizationLevel);
}

execBuffer
	.use(optipng, args.concat(['-out', execBuffer.dest(), execBuffer.src()]))
	.run(file.contents, function (err, buf) {
        ....
```

So basically the -strip all option is always used and the only option you take from the user is optimizationLevel ?

**Comment by shinnn** [comment]
> basically the -strip all option is always used and the only option you take from the user is optimizationLevel ?

Yes.
