### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by toddmedema** [imagemin/imagemin#157]
Looking to upgrade from an old version to imagemin 4.0.0, but I can't because I don't know what changed

Thank you,

Todd

**Comment by aziraphale** [comment]
Or, in my case, now looking to upgrade from 4.0.0 to 5.0.2 and have no idea what the reason was behind the semver major version bump, so have no idea if I'm going to be in for a world of hurt or not...

**Comment by shinnn** [comment]
https://github.com/imagemin/imagemin/releases

**Comment by toddmedema** [comment]
@shinn unless I'm missing something, wouldn't consider this closed - although that shows me when each release happened, what we'd really like is a list of major changes made in each version :)

**Comment by shinnn** [comment]
> a list of major changes

https://github.com/imagemin/imagemin/releases/tag/5.0.0

> made in each version

For pre-v5.0.0 versions, just read the commit log.

**Comment by toddmedema** [comment]
Yep! Though it looks like change information doesn't exist for the minor + patch releases since 5.0.0 (ie what changed in 5.2.2?)
