### ISSUE TITLE
ECONNREFUSED npm_install

### ISSUE THREAD

**Issue by aesteve** [imagemin/imagemin#161]
Hi, this is actually more a question than a bug report (please redirect me to a user group if more approriate)

When running `npm i imagemin` (or actually `webpack-image-loader`), I'm seeing this error :

```
RequestError: connect ECONNREFUSED 192.30.252.129:443
    at ClientRequest.<anonymous> (/.../node_modules/image-webpack-loader/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/got/index.js:69:21)
```

Same goes with other deps (optipng, jpegtran, ...)

I'm seeing this error on a specific (build) machine with no access to the internet it can only connects to a private npm registry. On my development machine with proxy settings + internet access it works perfectly fine, obviously.

I've seen https://github.com/imagemin/imagemin/issues/139 but I'm not really sure that's the same kind of issue, since it sounds to me like the origin of the problem is the lack of internet access (only local access).

Do you have any workaround in mind I could be testing ? 

Thanks in advance.

**Comment by kevva** [comment]
You need internet access to be able to download the necessary binaries needed for `imagemin` to work.
