### ISSUE TITLE
[TypeError: promisePipe(...) is not a function]

### ISSUE THREAD

**Issue by undefinederror** [imagemin/imagemin#167]
```js
var imagemin = require('imagemin');

imagemin(['src/img.jpg'], 'dist')
     .then(function (files) {
        console.log(files)
    })
     .catch(function(err) { 
        console.log(err);
    });
```

```js [TypeError: promisePipe(...) is not a function] ```

Using ```"imagemin": "^5.0.0" ``` on a clean project. Only package installed.

Am I doing something obviously wrong?

**Comment by kevva** [comment]
Yeah, you have to define some plugins using the `use` option (see [example](https://github.com/imagemin/imagemin#usage)).

It shouldn't throw though.

**Comment by undefinederror** [comment]
ah, gotcha :)
Thanks a lot for the quick reply.
