### ISSUE TITLE
Error: stream.on not a function

### ISSUE THREAD

**Issue by thatryan** [imagemin/imagemin#173]
I have seen this mentioned in a few other issues, but it looked to be resolved with current versions so I am lost. Am I missing something? 

Thank you.

Current versions:
* imagemin@4.0.0
* imagemin-cli@2.1.0
* imagemin-pngquant@5.0.0

Command:
`imagemin --plugin=pngquant bigimage.png > opt.png`

Error:
https://gist.github.com/thatryan/9a8bb079e04ddc9d436aafafa465241e

**Comment by kevva** [comment]
https://github.com/imagemin/imagemin/issues/164
