### ISSUE TITLE
Path weirdness

### ISSUE THREAD

**Issue by qm3ster** [imagemin/imagemin#174]
```js
imagemin(['staging/img/*.jpg'], 'staging/img/optimized', {use: [imageminMozjpeg()]}).then(() => {console.log('DONE: Images optimized')})
```
The above puts the output into `staging/img/optimized/staging/img/`
```js
imagemin(['staging/img/*.jpg'], 'optimized', {use: [imageminMozjpeg()]}).then(() => {console.log('DONE: Images optimized')})
```
The above puts the output into `optimized/staging/img/`

This would suggest the README tutorial is wrong, and `build/images/foo.jpg` would in fact be `build/images/images/foo.jpg`

**Comment by kevva** [comment]
https://github.com/imagemin/imagemin/issues/163
