### ISSUE TITLE
imagemin-cli freeze on win7x64

### ISSUE THREAD

**Issue by littleguga** [imagemin/imagemin#179]
![image](https://cloud.githubusercontent.com/assets/12018713/15608912/75558b6e-2425-11e6-9277-78a071654379.png)
![image](https://cloud.githubusercontent.com/assets/12018713/15608983/eca9f8d0-2425-11e6-8fc6-c5cfb60e8eba.png)

Try with git-bash and cygwin

**Comment by shinnn** [comment]
Don't use Windows 7. https://support.microsoft.com/en-us/lifecycle

**Comment by littleguga** [comment]
Hmm, not a great answer. Win7 support ends January 14, 2020.

For others: gulp-imagemin works fine, use it.

**Comment by kevva** [comment]
`gulp-imagemin` uses this module though.
