### ISSUE TITLE
Image minifying

### ISSUE THREAD

**Issue by sandysaders** [imagemin/imagemin#182]
I'm having a bit of trouble getting `imagemin`,  `imagemin-pngquant`, `imagemin-mozjpeg`, to work with node and express. I'm a bit of a noob, is there any example repository of this running in node that I can learn from? 

(sorry again for the noobyness)

**Comment by kevva** [comment]
I believe your glob is incorrect. Remove the space between `jpg, png`.

**Comment by jamestwiggle** [comment]
@kevva thank you for your response that fixed the issue it now returns:
```js
files:  [ { data: <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 06 6b 00 00 05 cc 08 03 00 00 00 f9 f5 48 8c 00 00 00 04 67 41 4d 41 00 00 b1 8f 0b fc 61 05 00 ... >,
    path: 'public/users/3/RavenJS.png' } ]
```

Does this mean that it minified the image and placed it in that location?

**Comment by kevva** [comment]
@sandysaders, yes :).
