### ISSUE TITLE
Add support for URLs in input parameter of imagemin

### ISSUE THREAD

**Issue by tarungarg546** [imagemin/imagemin#187]
Suppose a use case, 
Some one has a file which has a list of `urls` which points to an image and he/she wants to run `imagemin` on all of the `images`. Now, what he/she has to do in current scenerio is 
 
- Fetch images from Server
- Store them somewhere
- Give reference of stored files in `imagemin`
- Then, done.

Instead what we can do is,

- Let user give `url` as a input parameter.
- Check if it's a valid url by somewhat like `is-url`
- Fetch buffer data from that url 
- And then let our existing code handle that buffer data.

**Comment by kevva** [comment]
You can just do this:

```js
const querystring = require('querystring');
const got = require('got');
const imagemin = require('imagemin');

const urls = [
	'http://foo.com/unicorn.png?quality=65-80',
	'http://foo.com/asd.jpg?progressive=true',
	'http://foo.com/foo.gif?interlaced=true'
];

Promise.all(urls.map(url => {
	got(url).then(res => imagemin.buffer(res.body, querystring.parse(url)));
}));
```

**Comment by sampathkolanu** [comment]
is there a documentation on how to use url as input?

Because its not clear as to why you are using those params(quality, progressive, interlaced) in the urls
