### ISSUE TITLE
Temporary files not being deleted

### ISSUE THREAD

**Issue by zdila** [imagemin/imagemin#188]
Imagemin creates two temporary files per image. For example:
```
/tmp/34e6ca61-750f-400a-9972-5799d9579ec1
/tmp/ba2e3e5c-30a4-4ca5-8e6e-3b5b25949858
```

It never deletes them but it should.

**Comment by calmdev** [comment]
Did you figure this out? I'm using `imagemin.buffer` with `imagemin-pngquant` plugin and writing the resulting buffer to a file, but end up with the two additional tmp files in the current working directory of the running process. I can't figure how to prevent those two files from being created or target a different tmp directory. What am I overlooking here?

**Comment by calmdev** [comment]
@kevva is it related to `exec-buffer`? What causes these two files to be generated? How can they be cleaned up? Can you help or provide a link?

**Comment by calmdev** [comment]
Here's the issue I was running into, maybe it will help someone:
https://github.com/npm/npm/issues/4531

**Comment by shinnn** [comment]
This is an issue with Node.js itself.

**Comment by zdila** [comment]
@shinnn could you please provide us with the link pointing to that node issue?

**Comment by shinnn** [comment]
@zdila No issues for this problem haven't created yet. Anyone can submit it to https://github.com/nodejs/node/issues.

**Comment by devinus** [comment]
I'm also experiencing this in a Docker container.

**Comment by thrstn** [comment]
I think this issue should be looked into. For me this only happens with imagemin 5 but does not happen with 4.

**Comment by hielfx** [comment]
has someone fixed this issue somehow or created an issue in node/node?

**Comment by calmdev** [comment]
@hielfx try setting the `TMP_DIR` when starting your app.

Example, `TMPDIR=/tmp node server.js` that's what worked for me until there's a better solution.

**Comment by hielfx** [comment]
@calmdev Thanks! our problem was setting the `export TMPDIR=/tmp` and then using `sudo` instead of using `sudo TMPDIR=/tmp node ......`
