### ISSUE TITLE
Error building on windows

### ISSUE THREAD

**Issue by tarungarg546** [imagemin/imagemin#189]
[Issue](https://github.com/imagemin/imagemin-mozjpeg/issues/18)
Also when i am trying to build using `mozjpeg-bin` i am getting below error 
![image](https://cloud.githubusercontent.com/assets/10435209/17078254/4be6a822-510b-11e6-97ec-f997fd350cfc.png)

- Node version 6.3.0
- OS Windows 7
- Running in git bash..
- NPM version 3.10.3

**Comment by shinnn** [comment]
Duplicate of https://github.com/imagemin/imagemin-mozjpeg/issues/18
