### ISSUE TITLE
How to pass options to svgo plugin?

### ISSUE THREAD

**Issue by andrey-hohlov** [imagemin/imagemin#190]
Hi!

Same issue https://github.com/imagemin/imagemin/issues/95

```javascript
gulp.src(config.dest + '**/*.{png,jpg,gif,svg}')
  .pipe(imagemin({
    svgoPlugins: [
      { removeViewBox: true }
    ]
  }))
  .pipe(gulp.dest(config.dest))
```

I need to path option `removeUselessDefs: false` ( https://github.com/svg/svgo/issues/553 ) but cant.

**Comment by shinnn** [comment]
Read https://github.com/sindresorhus/gulp-imagemin/releases/tag/v3.0.0
