### ISSUE TITLE
buffer / stream issue - upgrading to current imagemin version

### ISSUE THREAD

**Issue by gmadar** [imagemin/imagemin#200]
In older version of imagemin I was able to pass the module a stream / buffer like this

`new ImageMinify().src(StreamOrBuffer).use(ImageMinify.jpegtran({progressive: true}))`

In the current version of imagemin there is no src function and calling the module will result in a promise.

I could not find how to achieve the same result in newer version of imagemin

Could it be done or that the support was removed?

**Comment by kevva** [comment]
You can supply a buffer using [imagemin.buffer](https://github.com/imagemin/imagemin#imageminbufferbuffer-options). Streams has never been supported.

**Comment by gmadar** [comment]
@kevva thanks!
