### ISSUE TITLE
Imagemin don't work

### ISSUE THREAD

**Issue by Fristing** [imagemin/imagemin#202]
Hi,
I don't know why but when i try to use imagemin it doesn't work. Why ?
``  const imagemin = require('imagemin');
  const imageminMozjpeg = require('imagemin-mozjpeg');
  const imageminPngquant = require('imagemin-pngquant');

  imagemin(['/fogclient/FOG-Client/app/assets/img/upload/profil/57c84e35ec786afe659ebc43.jpg'], '/fogclient/FOG-Client/app/assets/img/upload/profil', {
      plugins: [
              imageminMozjpeg(),
              imageminPngquant({quality: '65-80'})
          ]
      }).then(files => {
          console.log(files);
          //=> [{data: <Buffer 89 50 4e …>, path: 'build/images/foo.jpg'}, …]
      });
``
Thanks
Regards
Fristing

**Comment by kevva** [comment]
Please, include some errors in or it's impossible to narrow down what it could be. Try removing the `quality` option though since that one is known for causing issues.
