### ISSUE TITLE
imagemin fails silently when minifying animated gif of more then 9 frames

### ISSUE THREAD

**Issue by tomvanrossom** [imagemin/imagemin#203]
When using imagemin in gulp, it fails if I add animated gifs of more then 9 frames!?

If I replace the gif with one with less frames, everything is ok?

Any ideas why?

(This issue is a copy of one in [imagemin/gifsicle](https://github.com/imagemin/imagemin-gifsicle/issues/15))

**Comment by thisconnect** [comment]
I have no problem with 199 frames (248 × 249 pixels, file size: 1.41 MB, MIME type: image/gif, looped, 199 frames, 6.0 s) see https://github.com/thisconnect/imagemin-tests/tree/master/test/images (not using gulp, just plain imagemin)

**Comment by thisconnect** [comment]
care to share your gif with 10 frames?

**Comment by tomvanrossom** [comment]
http://i.imgur.com/M08busC.gif

**Comment by thisconnect** [comment]
using the default options this is the result

![gifsicle default](https://cloud.githubusercontent.com/assets/546900/18949896/adab8110-863d-11e6-8aff-e59f0a44a7ec.gif)

**Comment by thisconnect** [comment]
os, node version, imagemin + imagemin-gifsicle version ?

**Comment by thisconnect** [comment]
default options?

**Comment by tomvanrossom** [comment]
os: Debian 8.5
node: v4.3.1
gulp-imagemin: 3.0.1
gifsicle: 3.0.4

    gulp.task('images', function () {
        return gulp.src(config.app + 'content/images/**')
            .pipe(plumber({errorHandler: handleErrors}))
            .pipe(changed(config.dist + 'content/images'))
            .pipe(imagemin({optimizationLevel: 3, verbose: true}))
            //.pipe(debug({title: 'images:'}))
            .pipe(rev())
            .pipe(gulp.dest(config.dist + 'content/images'))
            .pipe(rev.manifest(config.revManifest, {
                base: config.dist,
                merge: true
            }))
            .pipe(gulp.dest(config.dist))
            .pipe(browserSync.reload({stream: true}));
    });

**Comment by shinnn** [comment]
http://www.catb.org/~esr/faqs/smart-questions.html#forum This is a [`gifsicle`](https://github.com/kohler/gifsicle)-related issue.
