### ISSUE TITLE
Feature request: iterative optimization with SSIM target

### ISSUE THREAD

**Issue by flash1293** [imagemin/imagemin#205]
It would be nice to have an option like `ssimQuality: 0.85` which iteratively increases compression (e.g. the `quality`-parameter for `imagemin-mozjpeg`) till the SSIM-index between the original image and the compressed one matches the desired value.

https://en.wikipedia.org/wiki/Structural_similarity
https://www.npmjs.com/package/image-ssim

**Comment by kevva** [comment]
That'd mean that we've to optimize the image multiple times until the SSIM index is matched which would be very slow.

**Comment by flash1293** [comment]
There could be a `maxRetries` option. At least for me it's a nice feature I would be willing to wait a few seconds for.

**Comment by sindresorhus** [comment]
Imagemin is already pretty slow. I think this would be better done as forks of the Imagemin plugins you need.
