### ISSUE TITLE
UnhandledPromiseRejectionWarning - imagemin hangs

### ISSUE THREAD

**Issue by mystikodesign** [imagemin/imagemin#210]
Using imagemin in a grunt build, was working perfectly until XCode 8.1 update. Now returns an error in terminal, and hangs:
(node:24085) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Expected a buffer
(node:24085) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:24085) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Expected a buffer
(node:24085) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Expected a buffer
(node:24085) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Expected a buffer

**Comment by shinnn** [comment]
Report it on https://github.com/gruntjs/grunt-contrib-imagemin/issues instead.
