### ISSUE TITLE
Couldn't load default plugin 'jpegtran

### ISSUE THREAD

**Issue by moahmn** [imagemin/imagemin#212]
that's my gulpfile code :
gulp.task('img',function(){
         gulp.src('img/**/*')
               .pipe(imagemin())
               .pipe(gulp.dest('dist/img'))

})
when i run the task ,it show me gulp-imagemin:Couldn't load default plugin 'jpegtran'
what's the problem is ?

**Comment by jpuncle** [comment]
What's your problem ?

**Comment by moahmn** [comment]
sorry,i forget to confirm edit button

**Comment by shinnn** [comment]
Should be reported on https://github.com/sindresorhus/gulp-imagemin/issues instead.
