### ISSUE TITLE
Using "gulp-imagemin": "^3.1.0" report error for GIF 

### ISSUE THREAD

**Issue by jianhua1982** [imagemin/imagemin#215]
Hey guys;
using "gulp-imagemin": "^3.1.0" with node version V6.3.1,  compress  [https://open.95516.com/s/open/image/ajax_loader_ads.gif](url)  report the following error,  it is ok for other image types (png and jpg).  

-------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Bogus Huffman table definition

    at Promise.all.then.arr (/Users/cup/new.h5.dev/patch/ch_w_ads/node_modules/execa/index.js:170:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by shinnn** [comment]
This is a [gifsicle](https://github.com/kohler/gifsicle)-related bug. Open a new issue on https://github.com/kohler/gifsicle/issues instead.
