### ISSUE TITLE
npm imagemin bug

### ISSUE THREAD

**Issue by hdcdstr8fwd** [imagemin/imagemin#221]
Npm install fails with build errors for jpegtran and optipng in a local project folder. Have tested with LTS and latest version of node both returns the same error.

I have tried to install these globally and the compile and the process runs as it should.
error is triggered any time imagemin is called in a local project

https://gist.github.com/hdcdstr8fwd/1a9e5dd538c8a0ec8db2c60271c03690#file-gistfile1-txt

npm -v prints: 3.10.10
node -v prints: v7.2.1 also tested with LTS version returns same error.
npm config get registry prints: https://registry.npmjs.org/
Windows, OS X/macOS, or Linux?: OS X 10.75

![error](https://cloud.githubusercontent.com/assets/23746188/21136113/3596bfc2-c11c-11e6-8a98-ded06b1cf0db.png)

**Comment by bxcn** [comment]
[14:37:12] Starting 'images'...
[14:37:13] Plumber found unhandled error:
 Error in plugin 'gulp-imagemin'
Message:
    ϵͳ�Ҳ���ָ����·����

Details:
    errno: ENOENT
    code: ENOENT
    syscall: spawn undefined
    killed: false
    stdout:
    stderr: ϵͳ�Ҳ���ָ����·����

    failed: true
    signal: null

**Comment by shinnn** [comment]
> OS X 10.75

Just upgrade the OS. ref. https://github.com/imagemin/jpegtran-bin/issues/69#issuecomment-162008355
