### ISSUE TITLE
Mozjpeg and optipng produce images with different sizes on mac and windows

### ISSUE THREAD

**Issue by shrpne** [imagemin/imagemin#223]
This leads to situation, when each commit to git write all changed images, so repository grows very fast.

Not all images have different size, about 90% of jpeg's and 50% of png's
These options used with gulp-imagemin
```
imagemin([
            mozjpeg({quality: 90}),
            imagemin.optipng({optimizationLevel: 5}),
            imagemin.svgo()
        ])
```
Modules used on mac and windows installed with npm-shrinkwrap.json:
gulp-imagemin@3.1.1
imagemin@5.2.2
imagemin-mozjpeg@6.0.0
mozjpeg@4.1.1
imagemin-optipng@5.2.1
optipng-bin@3.1.2

Not sure if it can be fixed and what the cause of the problem.

**Comment by stevendesu** [comment]
I'm not sure off-hand what would cause this (I don't know at a low level what mozjpeg and optipng are doing) although in my experience people don't commit post-processed files. Treat your pre-processed files as "source code" and your post-processed files as "compiled" (git ignore them) - then you don't have files randomly changing from one commit to the other unless you actually change the source file.

**Comment by shrpne** [comment]
@stevendesu thank you for reply, but gitignore compiled images and manual copying them on change is not very handy, beacuse there are a lot of images and they are changing pretty often.
However if I not find solution I will have to stuck with gitignore workaround

**Comment by sindresorhus** [comment]
Can be many factors. Sometimes we don't get the Windows updated as none of us use Windows. Different versions might result in different sizes.
