### ISSUE TITLE
TypeError: Promise.all is not a function

### ISSUE THREAD

**Issue by ajit-soman** [imagemin/imagemin#227]
I am getting error while minifying image.

<pre>TypeError: Promise.all is not a function
    at module.exports (/home/ajit/Desktop/ubuntu backup/demo-project/node_modules/globby/index.js:50:17)
    at module.exports (/home/ajit/Desktop/ubuntu backup/demo-project/node_modules/imagemin/index.js:53:9)
    at EventEmitter.minify (/home/ajit/Desktop/ubuntu backup/demo-project/application/controller-service-layer/controllers/ImgMinController.js:112:7)
</pre>

code in my controller:

<pre>
const imagemin = require("imagemin");

const imageminMozjpeg = require('imagemin-mozjpeg');
const imageminPngquant = require('imagemin-pngquant');

imagemin(['/home/ajit/Pictures/Screenshot from 2016-11-22 11:22:58.png'], '/home/ajit/Desktop/min-img', {
    plugins: [
        imageminMozjpeg(),
        imageminPngquant({
            quality: '65-80'
        })
    ]
}).then(files => {
    console.log(files);
});
</pre>

**Comment by shinnn** [comment]
@ajit-soman 

1. Show me the output of `node -v && npm -v`.
2. Are you using some JavaScript compilers (e.g. Babel) to run your code?

**Comment by ajit-soman** [comment]
<pre>ajit@ajit-Inspiron-N5050:~/git$ node -v
v6.9.1
ajit@ajit-Inspiron-N5050:~/git$ npm -v
3.10.8
</pre>

I just use **NODE_ENV=development node app.js** or some time **NODE_ENV=development nodemon app.js** to run code

**Comment by shinnn** [comment]
@ajit-soman Can you add `console.log(global.Promise)` just before `const imagemin = require("imagemin");` and show me the output?

**Comment by ajit-soman** [comment]
I got **[Function: defer]** as output

**Comment by shinnn** [comment]
@ajit-soman OK, That is the cause. The native `Promise` is overridden by another broken Promise implementation somewhere in your application or in one of the libraries you use. Usually `console.log(global.Promise)` outputs `[Function: Promise]`.

imagemin has nothing to do with this issue.
