### ISSUE TITLE
Node 6+ Support

### ISSUE THREAD

**Issue by donocode** [imagemin/imagemin#228]
The only information I could find about this is here https://github.com/imagemin/imagemin/issues/216#issuecomment-263870131

Is this true? Are there any plans for support? If so what needs to be done to support this and are pull requests for it likely to be merged?

If it's true and Node 6+ support is not intended then it should probably be notified in the readme as Node 6 is now the LTS release

**Comment by shinnn** [comment]
> Is this true?

No.

> Are there any plans for support?

Already.

**Comment by jdunk** [comment]
I don't see any other issues for Node 6+ support.

Could this one be reopened (or a new one created?) so that those who are interested can subscribe / check in later on status?

**Comment by shinnn** [comment]
No.

**Comment by donocode** [comment]
@jdunk your problem is you are using image-min and not imagemin, unfortunately the npm entry for image-min is just an outdated version and the github link still points here.

https://github.com/imagemin/imagemin/issues/216#issuecomment-274009471

**Comment by jdunk** [comment]
Ah, thank you @donocode for your actually useful comment :)

I wasn't using `image-min` directly, but I was using `gulp-image-optimization` which I see now does use `image-min`. ([link to their issue](https://github.com/firetix/gulp-image-optimization/issues/7) for anyone else who might come across this.)

Silly me, the `gulp-imagemin` package is far and away more popular; so I'll just switch to that. Thanks again.
