### ISSUE TITLE
Zero filesize when overwriting with Imagemin-cli 

### ISSUE THREAD

**Issue by samny** [imagemin/imagemin#230]
I would like to be able to save the optimized image in the same path, overwriting the original. But when I do this: `imagemin "images/image.jpg" > "images/image.jpg` the resulting file is empty.

Saving to a different path works fine `imagemin "images/image.jpg" > "images/image.min.jpg`

**Comment by shinnn** [comment]
Read https://github.com/imagemin/imagemin/issues/185#issuecomment-232609088. This is not an imagemin bug.
