### ISSUE TITLE
Support unquoted attributes

### ISSUE THREAD

**Issue by vzaidman** [imagemin/imagemin#233]
if you have svgs with unquoted attributes such as:
`xmlns="http://www.w3.org/2000/svg" width=20px height=20px`

The error: `Error in parsing SVG: Unquoted attribute value` is emitted.

i created a plugin to temporary fix this:
https://www.npmjs.com/package/xml-fix-loader

```
{
  test: /\.svg$/,
  use: [
    { loader: 'file-loader' },
    { loader: 'xml-fix-loader' }
  ]
}
```

bug was also opened on svgo:
https://github.com/svg/svgo/issues/678

**Comment by shinnn** [comment]
spam

* https://github.com/imagemin/imagemin/issues/233
* https://github.com/rpominov/svgo-loader/issues/9
* https://github.com/Klathmon/imagemin-webpack-plugin/issues/25

**Comment by vzaidman** [comment]
not a spam, i just got deeper and deeper to dependencies of dependencies to solve it :P
