### ISSUE TITLE
Make it work with webpack v2?

### ISSUE THREAD

**Issue by iDams** [imagemin/imagemin#234]
Hi,

I'm trying to make `imagemin` works with webpack v2 but I'm having trouble with it.
First I struggled with the error `Can't resolve 'fs' in 'imagemin/index.js'`
After googling it, I've found that it could be fixed with `transform-loader` and `brfs`.
I've set up my webpack config like this:

```
var path = require("path");

module.exports = {
  devtool: "cheap-module-eval-source-map",
  entry: ["./src/index"],
  output: {
    path: path.join(__dirname + "/public", "dist"),
    filename: "bundle.js"
  },
  module: {
    rules: [
      {
        include: path.resolve(__dirname, "node_modules/imagemin"),
        loader: "transform-loader?brfs",
        enforce: "post"
      },
      {
        test: /\.js$/,
        loader: "babel-loader",
        options: {
          presets: ["env"]
        },
        include: path.join(__dirname, "public"),
        exclude: [/node_modules/]
      }
    ]
  },
  resolve: {
    modules: ["node_modules", path.resolve(__dirname, "src")],
    extensions: [".js", ".css"]
  }
};
```

But I'm getting another error and I don't know how to fix it:
`Error: tried to statically call { readFile: [Function: readFile], readFileSync: [Function: readFileSync], readdir: [Function: readdir], readdirSync: [Function: readdirSync] } as a function` in `node_modules/static-modules/index.js`

Any idea how to make `imagemin` works with webpack?
Thanks!

**Comment by sindresorhus** [comment]
Imagemin isn't webpack'able. You should just exclude. This isn't the place to get Webpack support though.

**Comment by designbyadrian** [comment]
Imagemin isn't a webpack plugin. You'd want to use [image-webpack-loader](https://www.npmjs.com/package/image-webpack-loader ).
