### ISSUE TITLE
Can we implement a plugin for guetzli?

### ISSUE THREAD

**Issue by zeroasterisk** [imagemin/imagemin#235]
> [Guetzli](https://github.com/google/guetzli) is a JPEG encoder that aims for excellent compression density at high visual quality. Guetzli-generated images are typically 20-30% smaller than images of equivalent quality generated by libjpeg. Guetzli generates only sequential (nonprogressive) JPEGs due to faster decompression speeds they offer.

I am new to imagemin but I was wondering if this could be implemented as a plugin.  Thoughts?

If you have guides for how to wire in a new plugin, or a template to follow, let me know.

**Comment by thisconnect** [comment]
https://github.com/imagemin/imagemin-guetzli

**Comment by zeroasterisk** [comment]
Perfect thanks, sorry I'm blind and did not find that.

**Comment by thisconnect** [comment]
sidenote: guetzli means cookie in swiss german

**Comment by zeroasterisk** [comment]
Out of curiosity, can I just stuff a whole bunch of plugins into a single run, and imagemin figures out which one is best?
