### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18): Error: Error in file: xxx.jpg

### ISSUE THREAD

**Issue by summit2020** [imagemin/imagemin#242]
Module not compressing jpeg or jpg files but does with png's.

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18): Error: Error in file: xxx.jpg

Invalid or unsupported Targa file

**Comment by shinnn** [comment]
Insufficient info.
