### ISSUE TITLE
Images are not getting compressed to a great extent

### ISSUE THREAD

**Issue by sweetsamy21** [imagemin/imagemin#246]
I was able to compress images in my project. But when I do the same compression from https://tinypng.com/ there is a huge difference in the the size between the two. How can I decrease the size of my output files?

**Comment by kevva** [comment]
We are doing lossless compression by default. Try some other [plugins](https://www.npmjs.com/browse/keyword/imageminplugin) that does lossy compression instead.

**Comment by sweetsamy21** [comment]
I am using gulp-imagemin

**Comment by kevva** [comment]
You can still configure the plugin options, see https://github.com/sindresorhus/gulp-imagemin#custom-plugin-options. And you can use custom plugins too, https://github.com/sindresorhus/gulp-imagemin#plugins.

**Comment by sweetsamy21** [comment]
This is what my gulp task looks like.. but its hardly saving 20 kb from a 1.5 mb image...

gulp.task("images", function() {
    return gulp.src('../Common/assets/img/**/*')
        .pipe(imagemin([
            imagemin.gifsicle({interlaced: true}),
            imagemin.jpegtran({progressive: true}),
            imagemin.optipng({optimizationLevel: 7, 
                              bitDepthReduction: true, 
                              colorTypeReduction: true, 
                              paletteReduction: true, 
                              buffer: Buffer}),
            imagemin.svgo({plugins: [{removeViewBox: true}]})
          ]), {
            verbose: true
          })
        .pipe( gulp.dest(paths.artifactsBaseDir + '/img') );
});

**Comment by kevva** [comment]
What type of image? As I said, try other plugins that does more compression.

**Comment by sweetsamy21** [comment]
i am trying for png images..... I changed it but no luck... :(

gulp.task("images", function() {
    return gulp.src('../Common/assets/img/**/*')
        .pipe(imagemin({
            progressive: true,
            use: [pngquant()]
        }))
        .pipe( gulp.dest(paths.artifactsBaseDir + '/img') );
});

**Comment by kevva** [comment]
```js
.pipe(imagemin([
	imagemin.gifsicle({interlaced: true}),
	imagemin.jpegtran({progressive: true}),
	imagemin.svgo({plugins: [{removeViewBox: true}]}),
	imageminPngquant()
]))
```

**Comment by sweetsamy21** [comment]
Thanks Kevya.... I was putting the pngquant function out of imagemin... it works now... You are the best... :)
