### ISSUE TITLE
Error with Thumbs.db on Windows

### ISSUE THREAD

**Issue by bastienmoulia** [imagemin/imagemin#247]
Hi,

I use imagemin-cli 3.0.0 with `imagemin image/* --out-dir image` but i got the following error:

```
Error: Error in file: image/Thumbs.db
EPERM: operation not permitted, open 'myFolder\image\Thumbs.db'
```
I [see ](https://en.wikipedia.org/wiki/Windows_thumbnail_cache) that it comes from the thumbnails generated by Windows 7 but I think this file should be automaticaly black-listed from the list of the files to process.

**Comment by kevva** [comment]
Yup, agreed.

**Comment by sindresorhus** [comment]
We could use [`junk`](https://github.com/sindresorhus/junk) to filter out unwanted system files. PR welcome :)
