### ISSUE TITLE
Running the script on different platforms 

### ISSUE THREAD

**Issue by gkatsanos** [imagemin/imagemin#250]
Would Running the script on different platforms generate different binaries from the same source files and same options? (seems like it's the case on windows vs osx) 
Any way around it? (it's  git related issue.. Too many modified files at every commit)

**Comment by kevva** [comment]
I'm not sure, but I imagine running e.g. `optipng` on two different systems could result in different images, yes. Might differ if it's version mismatches too.

I wouldn't really keep generated files under version control though.

**Comment by gkatsanos** [comment]
Me neither but unfortunately it wasn't my decision, some folks still live in the era of "build and copy over the server" instead of deployment scripts. Thank you!
