### ISSUE TITLE
npm install bug error

### ISSUE THREAD

**Issue by KevinLandsberg** [imagemin/imagemin#251]
4901 verbose stack Error: gifsicle@0.1.7 postinstall: `node index.js`
4901 verbose stack Exit status 1
4901 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
4901 verbose stack     at emitTwo (events.js:106:13)
4901 verbose stack     at EventEmitter.emit (events.js:191:7)
4901 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:1$
4901 verbose stack     at emitTwo (events.js:106:13)
4901 verbose stack     at ChildProcess.emit (events.js:191:7)
4901 verbose stack     at maybeClose (internal/child_process.js:920:16)
4901 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
4902 verbose pkgid gifsicle@0.1.7
4903 verbose cwd /Users/kevin.landsberg/.npm/imageconvert/1.0.2/package/node_modules/gifsicle
4904 verbose Darwin 16.7.0
4905 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "imageconvert"
4906 verbose node v6.11.3
4907 verbose npm  v5.4.2
4908 error code ELIFECYCLE
4909 error errno 1
4910 error gifsicle@0.1.7 postinstall: `node index.js`
4910 error Exit status 1
4911 error Failed at the gifsicle@0.1.7 postinstall script.
4911 error This is probably not a problem with npm. There is likely additional logging output above.
4912 verbose exit [ 1, true ]

**Comment by kevva** [comment]
`gifsicle@0.1.7` is ancient. Try using a newer version.
