### ISSUE TITLE
Is development still active on this?

### ISSUE THREAD

**Issue by alexbudin** [imagemin/imagemin#257]
If development is not active or very slow it would be good for someone or a few others to be able to take care of this and move things along and answer PRs and deal with them.

Its understandable that there are other personal commitments and life in general gets in the way.

I am just trying to maybe open this discussion as this is a very popular module, used by many many people (great people, wonderful people - we all know who says this  :))  ). I know there are other plugins where work is being made, and maybe thats the reason response here is very slow, but it would be nice to get an update.

Thank you for everything.

Alex

**Comment by sindresorhus** [comment]
The project is not dead, but we could indeed use more people helping out.

Open issues: https://github.com/search?q=user%3Aimagemin&state=open&type=Issues&utf8=%E2%9C%93

**Comment by sindresorhus** [comment]
https://github.com/imagemin/imagemin/issues/385
