### ISSUE TITLE
I can not run imagemin give me error

### ISSUE THREAD

**Issue by ashikjs** [imagemin/imagemin#260]
# I can't run imagemin

`
PS C:\Users\ashikjs\Desktop\npm-es6-build-boilerplate> **npm run imagemin**

> npm-es6-build-boilerplate@1.1.0 imagemin C:\Users\ashikjs\Desktop\npm-es6-build-boilerplate
> imagemin src/images dist/images -p

Unknown plugin:

Did you forgot to install the plugin?
You can install it with:

  $ npm install -g imagemin-
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! npm-es6-build-boilerplate@1.1.0 imagemin: `imagemin src/images dist/images -p`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the npm-es6-build-boilerplate@1.1.0 imagemin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ashikjs\AppData\Roaming\npm-cache\_logs\2017-11-13T08_32_22_037Z-debug.log
`

**Comment by pixelasticity** [comment]
I'm getting the same error.

**Comment by BrotherDonkey** [comment]
I also go the same error

**Comment by EvanWieland** [comment]
Receiving same error.

**Comment by sindresorhus** [comment]
Per docs, the `-p` flag should be used with the name of an installed plugin you want to use.

**Comment by soso-maitha** [comment]
I am having same issue
