### ISSUE TITLE
Images are not optimized, where examples?

### ISSUE THREAD

**Issue by iamdubx** [imagemin/imagemin#263]
I used code from Docs

```js
const imagemin = require('imagemin');
const imageminJpegtran = require('imagemin-jpegtran');
const imageminPngquant = require('imagemin-pngquant');

imagemin(['images/*.{jpg,png}'], 'build/images', {
  plugins: [
    imageminJpegtran(),
    imageminPngquant({quality: '65-80'})
  ]
}).then(files => {
  console.log(files);
  //=> [{data: <Buffer 89 50 4e …>, path: 'build/images/foo.jpg'}, …]
})
```
This just copies files, that's all! 
Explain how to use it.

**Comment by iamdubx** [comment]
I am using it in Node app to optimize uploaded images. Not with Gulp/Grant. Why it isn't working?

**Comment by iamdubx** [comment]
Ok, I found `imagemin-mozjpeg` now it's working

**Comment by usamamashkoor** [comment]
@hackuun can you please explain how did you solve the issue...?

**Comment by Divyansh-Garg113** [comment]
@usamamashkoor imagemin-mozjpeg is a lossy plugin for imagemin (an alternative to lossless plugin imagemin-jpegtran). When I used imagemin-jpegtran with node-js I got many issues. But switching to imagemin-mozjpeg just solved the problem in a fly. 
You can look at this for more details about imagemin plugins for different format of images: https://web.dev/use-imagemin-to-compress-images

**Comment by jackson-elfers** [comment]
Very interesting, thanks for sharing!
