### ISSUE TITLE
How to access optimized buffer data without saving to a file?

### ISSUE THREAD

**Issue by iamdubx** [imagemin/imagemin#264]
Hi. I want to optimize uploaded images with `imagemin` and then pass it for resizing and stuff to `jimp`.

Is it possible? How to chain it? How to access buffer? I tried `files.data` but it says `undefined`

**Comment by sindresorhus** [comment]
Don't specify the `output` option and no files will be written and you can use the returned array of buffers. See the readme example and tests.
