### ISSUE TITLE
How to use imagemin with multer?

### ISSUE THREAD

**Issue by mrbudlong23** [imagemin/imagemin#274]
I've looked over the documentation but I'm still a little confused. When a user uploads an image (jpeg, png) with multer I want it to compress with imagemin, then overwrite the original, uncompressed file. Is this possible with imagemin? Thanks in advance.

**Comment by lightninglu10** [comment]
Why do you want to "overwrite" the file? Why not just use the different file object.

**Comment by kevva** [comment]
Should be possible by doing something like this:

```js
const fs = require('fs');
const imagemin = require('imagemin');

app.post('/foo', upload.single('unicorn'), async (req, res, next) => {
	const buf = await imagemin.buffer(req.file.buffer);
	fs.writeFileSync(req.file.filename, buf);
});
```

**Comment by etsraphael** [comment]
I try the last solution but it's not working right now. Anyone have another solution ?
