### ISSUE TITLE
imagemin-cli depents on deprecated gulp-util

### ISSUE THREAD

**Issue by Arjan-Oskam** [imagemin/imagemin#276]
The gulp-util is deprecated but still being used by imagemin-cli

It does work, for now, but as this post states:
https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

Every plugin should be stepping away from gulp-util

**Comment by evilebottnawi** [comment]
@sindresorhus friendly ping, can we move cli to other package?

**Comment by sindresorhus** [comment]
Neither `imagemin-cli` nor `imagein` depends on `gulp-util` anymore, so I'm not sure what this issue is about.
