### ISSUE TITLE
util deprecated in latest gulp release. imagemin is still dependent on util

### ISSUE THREAD

**Issue by worldserved** [imagemin/imagemin#288]
Hi since the release of the new gulp version which has deprecated util, which this plugin depends on, it is causing this plugin to throw errors. any plans to upgrade it from util dependency so we can continue to use it without being exposed to any vulnerability?
Thank you

**Comment by nunesgh** [comment]
[gulp-util has been deprecated](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5) and should be removed and replaced.

**Comment by XhmikosR** [comment]
imagemin doesn't use gulp-util, at least not anymore.
