### ISSUE TITLE
Should imagemin return the source when the result is larger?

### ISSUE THREAD

**Issue by tprobinson** [imagemin/imagemin#291]
Recently I've started using imagemin in an Express project of mine, with the [imagemin-gm](https://www.npmjs.com/package/imagemin-gm) plugin that allows for some manipulation of the source image before it's returned. However, while writing test cases I noticed that for example, converting a PNG to a JPG will return the original PNG because it is smaller.

While I can see the merit of always returning the smaller result in an image minification package, it can lead to confusion. In general, the user should get what they request rather than something else. Then, if the user wants to make that call of ignoring the converted result in favor of the original, they can do that themselves.

**Comment by TheodorTomas** [comment]
There is a PR that would fix this: https://github.com/imagemin/imagemin/pull/285
Waiting for it to be merged.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/imagemin/imagemin/commit/744a6c29415c8e46f5800f9fcb7380fb82c48286
