### ISSUE TITLE
EMFILE: too many open files

### ISSUE THREAD

**Issue by thany** [imagemin/imagemin#292]
I just tried to run imagemin-cli against a folder of ~18000 jpegs, so see what happens if I'd run it against the assets of a pretty huge website. It worked fine on a smaller set of about 1200 files.

I ran this command:
```
imagemin * --out-dir=./opti
```
And this is the output:
```
Error: EMFILE: too many open files, open '<filename>'
```
The `<filename>` is different each time. In the output folder, there are 8189 files after this. Also different each time. So more than half didn't make it through. I'm not sure if all of these files are optimized.

I noticed in the task manager, it's firing up WAY too many jpegtran.exe processes at once. My computer has a hyperthreaded quadcore cpu, so I would expect a maximum of 8 of these processes. But I saw dozens at the same time. Not only does this grind the computer to a nearly unusable state as long as those processes run in normal/default priority, but it may also be related to the above error.

I'm running Windows 10 x64, Node 8.11.4, npm 6.4.1, imagemin-cli 3.0.0.

Imagemin versions:
```
imagemin@5.3.1
| +-- imagemin-gifsicle@5.2.0
| +-- imagemin-jpegtran@5.0.2
| +-- imagemin-optipng@5.2.1
| +-- imagemin-svgo@5.2.4
| +-- ...
```

**Comment by sindresorhus** [comment]
In https://github.com/imagemin/imagemin/blob/744a6c29415c8e46f5800f9fcb7380fb82c48286/index.js#L56, we could use [`p-all`](https://github.com/sindresorhus/p-all) to limit the concurrency to something sensible.

**Comment by thany** [comment]
"Something sensible" will still end up an arbitrary number, I feel. Arbitrary numbers are not good, so perhaps it's possible to know how much concurrency is possible before hitting Node.js' own arbitrary restriction.

**Comment by sindresorhus** [comment]
It's not a Node.js restriction. The error is coming from the system. The limits will vary by system.

**Comment by thany** [comment]
Then we need to figure out how it varies, or how we can retrieve the max number of open files.

Alternatively, set the limit to something quite low, like the number of physical CPU cores. You'd probably not process more than (number of cores) files at the same time anyway.

**Comment by connorbrathwaite** [comment]
would something along these lines make sense?

```js
const numCores = require('os').cpus().length;

... pAll(paths.map(x => handleFile(x, output, opts)), {concurrency: numCores});
```

**Comment by qant** [comment]
Some one solve this problem?
