### ISSUE TITLE
TypeError in plugin "gulp-imagemin"

### ISSUE THREAD

**Issue by jonnitto** [imagemin/imagemin#295]
Since Version 4 I got always the error `Cannot read property 'path' of undefined`

OS: macOS 10.13.6
node: v10.10.0
npm: 6.4.1

**Comment by magicspon** [comment]
@jonnitto I'm getting this error as well.
```
TypeError in plugin "gulp-imagemin"
Message: Cannot read property 'path' of undefined
```

did you manage to resolve the issue?
