### ISSUE TITLE
Migrating from 4.0.0 to 6.0.0 - Uncaught TypeError: Imagemin is not a constructor

### ISSUE THREAD

**Issue by ceastman-ibm** [imagemin/imagemin#299]
I currently have this snippet of code that works with imagemin@4.0.0:

function minifyImages(srcPath, destPath, callback) {
  const imagemin = new Imagemin()
        .src(srcPath)
        .dest(destPath)
        .use(Imagemin.svgo())
        .use(Imagemin.jpegtran())
        .use(Imagemin.gifsicle())
        .use(Imagemin.optipng());
  imagemin.run(callback);
}

**Comment by 1000ch** [comment]
Please migrate the snippet according to [the newest usage](https://github.com/imagemin/imagemin#usage).
