### ISSUE TITLE
Improve documentation: if no size savings returns original

### ISSUE THREAD

**Issue by aprat84** [imagemin/imagemin#304]
Imagemin returns the optimized image only if it's size is lower than the original image.
I think this should be stated in big letters in the README.

I was getting mad cause webp plugin was returning jpeg... Thanks to this issue i saw the light:
https://github.com/imagemin/imagemin-webp/issues/13

https://github.com/imagemin/imagemin/blob/9ef134d7dd9b3e0e043a407e0fc0d8032d2d5d20/index.js#L24
https://github.com/imagemin/imagemin/blob/9ef134d7dd9b3e0e043a407e0fc0d8032d2d5d20/index.js#L73

**Comment by TheodorTomas** [comment]
In my opinion this should not be the case. The expected behaviour is that all jpg/png images be converted to WebP regardless of the potential savings. Or in the very least there should be an option to force a WebP file being created.

**Comment by aprat84** [comment]
I know, there's a PR https://github.com/imagemin/imagemin/pull/285 opened about this, but it was opened in July 16th and not yet merged...
The least that could be made is to inform anyone who wants to use this lib about it's behavior, imho.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/imagemin/imagemin/commit/744a6c29415c8e46f5800f9fcb7380fb82c48286
