### ISSUE TITLE
imagemin-cli 4.x became unusable after updateing to imagemin-svgo because of breaking changes

### ISSUE THREAD

**Issue by RiZKiT** [imagemin/imagemin#307]
When I update to imagemin-cli 4.x, imagemin-svgo as a dependency will be updated too. 

There was a breaking change that removes the viewbox from svg's by default. Because I cannot change the plugin behaviour via cli, I cannot update.

Related:
- https://github.com/imagemin/imagemin/issues/171 (options for cli)
- https://github.com/imagemin/imagemin/issues/296 (config file for cli)

**Comment by sindresorhus** [comment]
Closing as #171 and #296 already covers the solutions to this issue.
