### ISSUE TITLE
Consider switching globby to node-glob

### ISSUE THREAD

**Issue by maxnordlund** [imagemin/imagemin#314]
Currently imagemin's [install size](https://packagephobia.now.sh/result?p=imagemin) is 2.70MB. After #313 this will go up ~1MB, thanks to globby pulling in fast-glob. On the flip side node-glob is very lightweight, so switching to that would save a fair few bytes every time this is downloaded from npm. At the time of writing this this is an impressive 629 886 times a week, that turns into ~1.9 terabyte a week saved. (Assuming 3MB saved, from the numbers below)

Size      | Link
--------|--------------
3.27MB | https://packagephobia.now.sh/result?p=globby
197kB   | https://packagephobia.now.sh/result?p=node-glob

**Comment by sindresorhus** [comment]
This has been fixed in the latest `globby` release: https://packagephobia.now.sh/result?p=globby

**Comment by maxnordlund** [comment]
It's still a bit larger then node-glob but what an improvement, thanks man :)
