### ISSUE TITLE
Breaks google svg

### ISSUE THREAD

**Issue by rolurq** [imagemin/imagemin#317]
I'm using imagemin with webpack, and seems fine, except for the google svg. This is how the original svg looks like
![google-icon](https://user-images.githubusercontent.com/13684824/56246356-d0aac680-606f-11e9-8624-77a38b8d52c8.png)
and this is what imagemin produces
![google-icon](https://user-images.githubusercontent.com/13684824/56246496-22535100-6070-11e9-8a02-360c63f88f5b.png)

this are the two svg
[google.zip](https://github.com/imagemin/imagemin/files/3087046/google.zip)

**Comment by RiZKiT** [comment]
I looked at the icon, it uses inline styles, these will be stripped/optimized by "svgo", the optimnizer used by image min for svgs. The options I can think of:

- use inlineStyle: false for svgo: https://github.com/imagemin/imagemin-svgo#usage
- exclude icon from optimization
- do not optimize svg at all
- change the icon, so it does not rely on clip path or put a tylesheet beside the icon that 
- put a stylesheet beside the icon to fix it

**Comment by XhmikosR** [comment]
Not an issue with imagemin, svgo issues should be reported there.
