### ISSUE TITLE
Cannot write multiple files to stdout

### ISSUE THREAD

**Issue by mjolewis** [imagemin/imagemin#319]
imagemin-cli@4.0.1 is unable to write multiple files. Any ideas on how to get around this other than downgrading to @3.0.0?

```
Cannot write multiple files to stdout
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by RobertoQuintero** [comment]
Cannot write multiple files to stdout, specify a `--out-dir`

I just wrote --out-dir instead -o and that worked
before:   imagemin \"./src/img/\" -o ./public/img/
after:   imagemin \"./src/img/\" --out-dir ./public/img/
