### ISSUE TITLE
viewBox attribute removed despite using `removeViewBox: false`

### ISSUE THREAD

**Issue by jelmerdemaat** [imagemin/imagemin#320]
Hi!

I don't know for sure if this is an issue with imagemin, gulp-imagemin, or svgo, but it seems to be with imagemin. The viewBox attribute on my svg's is (sometimes) removed despite using the `removeViewBox: false` setting.

I have a reduced test case here:
https://codesandbox.io/s/imagemin-svgo-viewbox-test-i5mlf

You can fork it, and restart the server using the server panel (on the left) to start off the script (I don't how else non-owners can restart the script).

Current input starts with (_test.svg_):

`<svg xmlns="http://www.w3.org/2000/svg" width="11" height="23" viewBox="0 0 11 23"...`

Current output starts with (_output/test.svg_):

`<svg xmlns="http://www.w3.org/2000/svg" width="11" height="23"><path...`

What's important: I have tested it with the SVGO cli, and there the problem does not exist. Try:

`$ svgo input.svg -o output.svg --disable=removeViewBox`

With and without the ` --disable=removeViewBox` part.

So it really seems to be in this imagemin library. I myself wouldn't know where to start looking, but I would be glad to help fix it.

Thanks in advance!

**Comment by XhmikosR** [comment]
Not an issue with imagemin. Make sure you pass all of your options properly, you aren't using the API properly.

**Comment by jelmerdemaat** [comment]
Which API? Of the gulp plugin?

**Comment by XhmikosR** [comment]
Yeah. It should be `imagemin.svgo(plugins: [foo: false])`
