### ISSUE TITLE
升级之后不能识别二进制文件

### ISSUE THREAD

**Issue by aopama** [imagemin/imagemin#326]
(node:16855) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Error occurred when handling file: cache_temp/*.{jpg,png}

Error: /root/mx/project/node_modules/pngquant-bin/vendor/pngquant: /root/mx/project/node_modules/pngquant-bin/vendor/pngquant: 无法执行二进制文件

    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
(node:16855) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aopama** [comment]
发现imagemin是使用二进制可执行文件来对图片进行压缩的，执行二进制的函数是child_process.spawn，这个函数对于文件路径有限制，因为electron打包后，会把依赖项压缩成一个文件，导致这个函数判断路径时报错，对于这个问题，如果是自己的代码中使用了二进制文件，则可以将child_process.spawn替换为child_process.execFile函数来执行二进制文件。
但是之前版本是好的啊不用弄啊

**Comment by aopama** [comment]
能不能更新一版在

**Comment by TangChang** [comment]
你好，请问解决了么？

**Comment by RoderickQiu** [comment]
As for now (2023), a yarn patch will be the best solution.
```
diff --git a/index.js b/index.js
index d94125310c696f2f56dd4439d2200f4e29951aea..61721d359df2e437bac45a46629ed4fd55be7ef8 100644
--- a/index.js
+++ b/index.js
@@ -77,7 +77,7 @@ const execa = (file, args, options) => {
 
 	let spawned;
 	try {
-		spawned = childProcess.spawn(parsed.file, parsed.args, parsed.options);
+		spawned = childProcess.execFile(parsed.file, parsed.args, parsed.options);
 	} catch (error) {
 		// Ensure the returned error is always both a promise and a child process
 		const dummySpawned = new childProcess.ChildProcess();
@@ -166,7 +166,7 @@ module.exports.sync = (file, args, options) => {
 
 	let result;
 	try {
-		result = childProcess.spawnSync(parsed.file, parsed.args, parsed.options);
+		result = childProcess.execFileSync(parsed.file, parsed.args, parsed.options);
 	} catch (error) {
 		throw makeError({
 			error,

```

Anyway, don't you think it a bad practice to use Chinese to send an issue to an european qwq
