### ISSUE TITLE
Using imagemin synchronously on cli applications

### ISSUE THREAD

**Issue by edertone** [imagemin/imagemin#333]
So i am writting a node cli application that executes several sequential processes. Is there any way to execute imagemin in a synchronous way? 

For example, run this:

imagemin([imageFile], "output", {
            plugins: [
                imageminJpegtran({
                    progressive: true
                }),
                imageminPngquant({
                    quality: [0.8, 0.9],
                    speed: 1, 
                    floyd: 1 
                })
            ]
        });

// Wait till it finishes, and have the result here
//... Continue with the guarantee that image processing has finished

**Comment by kevva** [comment]
Yes, have a look at https://github.com/imagemin/imagemin-cli/blob/master/cli.js#L106-L112 :).
