### ISSUE TITLE
Same size before and after 

### ISSUE THREAD

**Issue by etsraphael** [imagemin/imagemin#345]
Hi, I don't know why but my file keep almost the same size before and after the compression. 

Thank you if you have the solution : 

`

    const storage = inMemoryStorage();
    storage.single('file')(req, res, async () => {

      try {
        console.log(req.file.buffer.length)  // it's 11152324
        const buf = await imagemin.buffer(req.file.buffer, {
          plugins: [
            imageminJpegtran(),
            imageminPngquant({quality: 0.6})
          ]
        })
        console.log(buf.length);  // it's 11149178
        // end

       ....
      }
      catch (err) {
        this.logger.error(err)
        return res.status(500).json({ status: 500, message: 'internal_server_error' })
      }
    })
`

So I think I really have a problem during the compression, I really want to compress 50% if it's possible

**Comment by esbeeb** [comment]
Formats like .png and .jpg are **already** (internally) compressed.  It's a serious waste of CPU cycles to re-compress them (as in, compress them yet a second time).  **You are likely to only save like 1 or 2% of the file size by this second attempt at compression.**

Try compressing a few .jpgs and .pngs laying around on your computer for yourself, and you'll see that I'm not kidding.

**Comment by 1000ch** [comment]
As you know, how images are compressed depends on what/how we apply.

- PNG: I recommend you to use [imagemin-pngquant](https://github.com/imagemin/imagemin-pngquant) and [imagemin-optipng](https://github.com/imagemin/imagemin-pngquant) with some configurations.
- JPG: I recommend you to use [imagemin-mozjpeg](https://github.com/imagemin/imagemin-mozjpeg) with some configurations.

If you could not get results even after trying them, those images seems to be optimized enough.
