### ISSUE TITLE
webpack build err: Invalid shorthand property initializer

### ISSUE THREAD

**Issue by jane-rose** [imagemin/imagemin#347]
my webpack  config  is below:
![75609458-a062fe00-5b43-11ea-95f9-6e6c5d5960d3](https://user-images.githubusercontent.com/33253363/75839321-8d7e5100-5e03-11ea-8241-d75fdbdbbe4e.png)

when i build, webpack error is

`ERROR in ./src/assets/img/thankyou/xxx Module build failed (from ./node_modules/image-webpack-loader/index.js): /var/lib/jenkins/workspace/static-snapmakerX/node_modules/imagemin/index.js:15 const handleFile = async (sourcePath, {destination, plugins = []}) => { ^^^^^^^^^^^^ SyntaxError: Invalid shorthand property initializer`

Is anyone help me ? thx!
My webpack version is 4.8.3, and babel7

**Comment by guiguipp** [comment]
I had a similar issue on node 8, it is not happening since I upgraded to node 12. If you are on an older version of node, can you try upgrading and see if that fixes this issue?
