### ISSUE TITLE
Is there a way to use an input and output stream?

### ISSUE THREAD

**Issue by jackson-elfers** [imagemin/imagemin#349]
I'd rather not write this to file, I'd like to just stream it up to my storage system. It appears this has been discussed before. I might fork and tinker with that possibility. Better yet, I'll use this in a lambda function with s3 so I won't have to run it on the server.

**Comment by jackson-elfers** [comment]
Ok I solved my own problems see ya!

**Comment by getkey** [comment]
![TitsMcGee4782](https://www.optipess.com/wp-content/uploads/2018/10/2018-10-15-932_TitsMcGee4782_800.png)

Use [concat-stream](https://www.npmjs.com/package/concat-stream).

**Comment by jackson-elfers** [comment]
😹😹😹 Yeah that was a useless issue. Thanks!

**Comment by getkey** [comment]
No worries, it didn't take me too much time to find out about concat-stream. Have a good day 🙂
