### ISSUE TITLE
Does't work on windows

### ISSUE THREAD

**Issue by xusai2014** [imagemin/imagemin#352]
```js
const imagemin = require('imagemin');
const imageminOptipng = require('imagemin-optipng');

(async () => {
  const files = await imagemin(['loginbg.png'], {
    destination: 'build/images',
    plugins: [
      imageminOptipng()
    ]
  }).then(function(res) {
    console.log(res, 'res')
  }, function(err) {
    console.log(err, 'err')
  });

  console.log(files);
  //=> [{data: <Buffer 89 50 4e …>, destinationPath: 'build/images/foo.jpg'}, …]
})();
```

![image](https://user-images.githubusercontent.com/8156165/80070744-0da87380-8576-11ea-9b81-78913e393737.png)

**Comment by xusai2014** [comment]
Why  the  result is emty arrary?

I can't get any tips about real situation;

**Comment by awwit** [comment]
@xusai2014 you specified the path to one file, maybe the script cannot find it ?

**Comment by BayBreezy** [comment]
I am having the same issue. my code is similar to that of the OP. any updates?

**Comment by gdutjason** [comment]
I am having the same issue. File path is constructed by fs,  but get an emty arrary without any error or tips

**Comment by VitalyKrenel** [comment]
Hey @sindresorhus! Do you mind helping us out a bit with the issue? 

I tried to run the tests on Windows 10 (1903), and looks like two of them are failing. More specifically these:

![image](https://user-images.githubusercontent.com/17354709/82719642-21e6aa00-9cb5-11ea-9a7e-f3d32715f854.png)

In meanwhile, I'll continue looking into them, but it would be great if you could share your thoughts on why it might be happening.

**Comment by VitalyKrenel** [comment]
Alright, it is the paths handling problem: `imagemin` relies on `globby` package which expects the forward slashes within the file name, instead of backward ones (which are used on Windows).

@sindresorhus  I've suggested the PR with the fix, could you check it out please?
https://github.com/imagemin/imagemin/pull/358

**Comment by VitalyKrenel** [comment]
@1000ch @kevva Hey guys!
Could you please take a look at the PR? Not a huge thing, but definitely would be helpful for the Windows user (including me)

**Comment by 1000ch** [comment]
@xusai2014 

(I modified your code snippet slightly)

```js
console.log(files);
  //=> [{data: <Buffer 89 50 4e …>, destinationPath: 'build/images/foo.jpg'}, …]
```

> Why the result is emty arrary?

I think the result is not empty array.

**Comment by alex-drocks** [comment]
same problem for me on windows.

I was only able to make it work by replacing slahes to unix format like that:
```JavaScript
const compressedFile = await imagemin([originalFilePath.replace(/\\/g, '/')], {
```

**Comment by edertone** [comment]
Had to spend a lot of time till i found this bug, also on windows. Only solution for me that worked was to format the paths to a / unix style when passing them to the imagemin method.

**Comment by bkarlson** [comment]
same problem, just wasted an hour on this. IF this issue is not fixed, it should be described in docs.

**Comment by bkarlson** [comment]
Setting `glob: false` works in case globbing is not necessary, but why not just accept https://github.com/imagemin/imagemin/pull/358? @1000ch please, thanks.

**Comment by JaimeGSandoval** [comment]
@bkarlson Thank you! That worked well for me. I  should actually read the docs instead of just skimming over them.
