### ISSUE TITLE
TypeError: Expected an `Array`, got `string`

### ISSUE THREAD

**Issue by munitioner** [imagemin/imagemin#371]
I have successfully installed imagemin and imagemin-pngquant, but an error is reported when running “TypeError: Expected an `Array`, got `string`”

**Comment by cll123456** [comment]
you need use string[] ,such as [path]

**Comment by cherryleafroad** [comment]
It is broken. Using the CLI app

The basic example fails.
`imagemin 1.png --plugin.pngquant.quality={0.1,0.2} > 1-test.png`

```
ArgumentError: Expected `options.quality` to be of type `array` but received type `string`
    at u (...\nodejs\node_modules\imagemin-pngquant\node_modules\ow\dist\source\index.js:1:12174)
    at ...\nodejs\node_modules\imagemin-pngquant\index.js:35:3
    at ...\nodejs\node_modules\imagemin-cli\node_modules\p-pipe\index.js:12:25
    at handleFile (...\nodejs\node_modules\imagemin-cli\node_modules\imagemin\index.js:21:54)
    at async ...\nodejs\node_modules\imagemin-cli\node_modules\imagemin\index.js:54:13
    at async Promise.all (index 0)
    at async run (...\nodejs\node_modules\imagemin-cli\cli.js:90:11)
    at async ...\nodejs\node_modules\imagemin-cli\cli.js:122:3
```

If you take a hint from the error message and use `--plugin.pngquant.options.quality={0.1,0.2}`, then it works, HOWEVER if you play around with the setting, you'll soon realize that it isn't actually setting the quality and does NOTHING. `--plugin=pngquant` does just as much. It is broken. :/
