### ISSUE TITLE
What meaning the options of glob?

### ISSUE THREAD

**Issue by cll123456** [imagemin/imagemin#375]
` const files = await imagemin(['my absolute path'], {
                glob: false,
                destination: 'my absolute file folder',
                plugins: [
                    imageminJpegtran({
                        quality: 70,
                    }),
                    imageminPngquant({
                        quality: [0.6, 0.8]
                    })
                ]
            });`

When i use `glob: true` ,the code doesn't work, but i use `glob:false` , it can press the img. I want to know the options is meaning.  Thanks to everyone who found out about my problem

**Comment by leesei** [comment]
If `glob` is true, the path is passed to [`globby`](https://github.com/sindresorhus/globby), which resolves "images/**/*" to a bunch of files.

Did any of your paths happens to contain the `*` character?
