### ISSUE TITLE
Code runs but nothing seems to happen

### ISSUE THREAD

**Issue by DavidFaizulaev** [imagemin/imagemin#388]
This is my function code, when I run it, it finishes, but no output exists in `files` and the 'compressed-images' folder is empty.

```
'use strict';
import imagemin from 'imagemin';
import imageminJpegtran from 'imagemin-jpegtran';

export async function compressImage(): Promise<void> {

	const files = await imagemin(['../David.jpeg'], {
		destination: '../compressed-images',
		plugins: [
			imageminJpegtran(),
		]
	});

	console.log(JSON.stringify(files, null, 1));
}
```

imagemin v7.0.1
node v14.15.4
typescript v4.3.4

Please advise what am I doing wrong.

**Comment by mnakhaei** [comment]
same issue:
```
      page.screenshot({ omitBackground: true }).then(screenshot => {
        imagemin.buffer(<Buffer>screenshot).then(compressedImage=>{
          console.log(compressedImage.length,(<Buffer>screenshot).length);
        })

```

- version 7.0.1
- node v14.15.4

**Comment by DavidFaizulaev** [comment]
Issue was due to the path no being passed as obsolete path. This is the working code:

`const pv = path.join(__dirname, '../../David.jpeg');

const files = await imagemin([pv], {
    destination: path.join(__dirname, '../../compressed-images'),
    plugins: [
        imageminMozjpeg({quality: 50})
    ]
});`
