### ISSUE TITLE
Error: Cannot find module node:buffer

### ISSUE THREAD

**Issue by Tenpi** [imagemin/imagemin#395]
Cannot import, it fails with the error "Error: Cannot find module node:buffer". This syntax is strange. Shouldn't it be `import {Buffer} from "buffer"`?

Node version: 16.3.0
Typescript version: 4.1.3

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/globby/pull/196#issuecomment-959801239

Try upgrading your TS version.
