### ISSUE TITLE
Question : Can we use this package in React-Native as well ?

### ISSUE THREAD

**Issue by MuhammadAbdullah54321** [imagemin/imagemin#402]

**Comment by Roka20012** [comment]
@MuhammadAbdullah54321  I think yes, because the expo suggest it as an alternative of the expo-optimize package

![image](https://user-images.githubusercontent.com/32239452/214103448-3baca60d-fb57-406e-a9d4-29d59809f992.png)



https://www.npmjs.com/package/expo-optimize

**Comment by sindresorhus** [comment]
No, it requires Node.js.
