### ISSUE TITLE
mozjpeg

### ISSUE THREAD

**Issue by sindresorhus** [imagemin/imagemin#41]
We might want to make `mozjpeg` the default JPEG minifier now that it's better at compressing than jpegtran: https://github.com/mozilla/mozjpeg/releases

**Comment by shinnn** [comment]
This plan has been canceled? (8d493ceacb7ca4cf846efa70ffcef9affc822c81 seems to be reverted.)

**Comment by kevva** [comment]
We'll use it in the next major release.

**Comment by kevva** [comment]
I'll close this as we aren't bundling any plugins by default anymore.
