### ISSUE TITLE
imagemin not work (ERR_REQUIRE_ESM)

### ISSUE THREAD

**Issue by Omarhkhamis** [imagemin/imagemin#414]
Hi, 
I try Imagemin library but show this error when I start 
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\omar0\Desktop\gulp-project\node_modules\gulp-imagemin\index.js from C:\Users\gulpfile.js not supported.
Instead change the require of index.js in C:\Users\gulpfile.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\gulpfile.js:28:18) {
  code: 'ERR_REQUIRE_ESM'
  
  This code
  
   `const { src, dest, series, watch } = require("gulp");
   const imagemin = require("gulp-imagemin");
function imageMinify() {
  return src("./frontend/src/images/*")
    .pipe(imagemin())
    .pipe(dest("./frontend/dist/images/"));
}

function watchTask() {
  watch([
    "./frontend/src/images/*",
  ]),
    series( imageMinify);
}

exports.default = series(imageMinify, watchTask);

   
`

**Comment by MikhailTo** [comment]
let imagemin; import("gulp-imagemin").then(res => { imagemin = res;}); //const imagemin = require("gulp-imagemin");

**Comment by whenmoon** [comment]
> `let imagemin; import("gulp-imagemin").then(res => { imagemin = res;}); //const imagemin = require("gulp-imagemin");`

After doing this I get the same error but for the other package:

> Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/gulp-imagemin/index.j

**Comment by MikhailTo** [comment]
> > `let imagemin; import("gulp-imagemin").then(res => { imagemin = res;}); //const imagemin = require("gulp-imagemin");`
> 
> After doing this I get the same error but for the other package:
> 
> > Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/gulp-imagemin/index.j



1. Remove gulp-imagemin and write in package.json  
```
"overrides": {
	"gulp-imagemin": "7.1.0"
}, 
```
2. Rewrite gulpfile with import and use 9th version

**Comment by franzos** [comment]
For ESM, make sure to make to add `module` to your `package.json` like this:

```json
{
  "type": "module",
  "dependencies": {
    "bulma": "^0.9.4",
    "gulp": "^5.0.0",
    "gulp-clean-css": "^4.3.0",
    "gulp-concat": "^2.6.1",
    "gulp-imagemin": "^9.0.0",
    "gulp-uglify-es": "^3.0.0",
    "lunr": "^2.3.9",
    "pump": "^3.0.0",
    "vue": "^2.7.15"
  },
  "scripts": {
    "build": "gulp"
  }
}
```

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
