### ISSUE TITLE
Use Base64 Encoded String

### ISSUE THREAD

**Issue by hibooboo2** [imagemin/imagemin#64]
Is it possible to use base64 encoded strings instead of files. So that i can not use a file.

EX:

Pull a base64 string from json acquired via ajax then use imagemin to optimize so i can determine if original image is already optimized?

**Comment by wpitallo** [comment]
Did you ever get this working?

**Comment by hibooboo2** [comment]
No that I remember.. But no idea was 5 years ago., :| Now I do golang the javascript stuff was dabbling as a new developer.
