### ISSUE TITLE
stream usage

### ISSUE THREAD

**Issue by samdaltonmaag** [imagemin/imagemin#76]
How can I pipe the stream in the callback? I'd expect to see something here, but I only get 'finished'.

````js
var fs = require('fs'),
    imagemin = require('imagemin');

var i = new imagemin().src('test.jpg').use(imagemin.jpegtran());

i.run(function (e, files, stream) {
  stream.pipe(process.stdout);
});

i.on('end', function (data) {
  console.log('finished');
});
````

**Comment by UmeshSingla** [comment]
@kevva, I need help with the same thing, I don't get the usage of stream in here, I need to put that stream to S3, but I couldn't find any reference, urgent help is appreciated :)

**Comment by kevva** [comment]
@UmeshSingla, sorry for the late response. The stream usage currently doesn't work since it's inside the callback.

**Comment by usamamashkoor** [comment]
did you find any solution...?
