### ISSUE TITLE
Grunt task could not run 

### ISSUE THREAD

**Issue by TonyWuLihu** [imagemin/imagemin#77]
I have tried to setup a jenkins build job, but always fail with below error : 
[33mWarning: Error: Command failed: /var/lib/jenkins/jobs/Engine_UI3.0_cloudplatform_dev/workspace/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng -strip all -quiet -clobber -o 3 -out /tmp/b2502d8e-8783-4771-88b8-3ebc24099c07 /tmp/25746a83-2795-4391-8c40-2557f3f95f54
    /var/lib/jenkins/jobs/Engine_UI3.0_cloudplatform_dev/workspace/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /var/lib/jenkins/jobs/Engine_UI3.0_cloudplatform_dev/workspace/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng)
     in file assets/images/cloud/feature-book.png Use --force to continue.[39m

```
[31mAborted due to warnings.[39m


Execution Time (2014-12-11 15:46:18 UTC)
loading tasks   14ms  ▇ 2%
imagemin:dist  726ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 98%
Total 741ms Use --force to continue.[39m

    [31mAborted due to warnings.[39m
```

Execution Time (2014-12-11 15:46:14 UTC)
loading tasks     11ms  0%
clean:dist       119ms  ▇▇ 3%
wiredep:app      492ms  ▇▇▇▇▇ 10%
wiredep:sass      46ms  ▇ 1%
concurrent:dist     4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 86%
Total 4.7s

Build step 'Execute shell' marked build as failure
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Finished: FAILURE

The OS is Cent 6.5

**Comment by steelx** [comment]
Im facing similar problem on CentOS.

```
Warning: Running "imagemin:dist" (imagemin) task
16:18:59.004     Warning: Error: Command failed: /var/lib/go-agent/pipelines/FlockSupport/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /var/lib/go-agent/pipelines/FlockSupport/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng)
16:18:59.004      in file app/images/flock-logo.png Use --force to continue.
16:18:59.004     
16:18:59.004     Aborted due to warnings.

```

**Comment by shinnn** [comment]
grunt-contrib-imagemin depends on too outdated imagemin. Open a pull request "Update imagemin to 5.x" to https://github.com/gruntjs/grunt-contrib-imagemin/pulls then this problem will be fixed.
