### ISSUE TITLE
Add recursive option to imagemin bin

### ISSUE THREAD

**Issue by mathpere** [imagemin/imagemin#78]
Hi,

Would it be useful to add -R (recursive) option?

```
# source:

# src/img/icons/icon1.png
# src/img/icons/icon2.png
# src/img/icons/icon3.png
# src/img/patterns/pattern1.png
# src/img/patterns/pattern2.png
# src/img/patterns/pattern3.png

imagemin -R src/img dist/img 

# would produce:

# dist/img/icons/icon1.png
# dist/img/icons/icon2.png
# dist/img/icons/icon3.png
# dist/img/patterns/pattern1.png
# dist/img/patterns/pattern2.png
# dist/img/patterns/pattern3.png
```

**Comment by zanona** [comment]
I am sorry, I couldn't understand how this issue has been closed?
Apparently even when using globbing, the directory original structure is not kept and all images are expanded into the target?

**Comment by kevva** [comment]
It was closed by a commit. It worked then. Not sure what broke since.

**Comment by jackwanders** [comment]
as of version `1.0.0` this still appears to be an issue. `imagemin src/**/* dist` does not preserve the directory structure of the source paths.

**Comment by abbajbryant** [comment]
Any chance this is going to be addressed? I am using the latest and am getting a flat directory of files instead of a copied sub-directory structure as above.

**Comment by manuelbieh** [comment]
Why has this issue been closed? `imagemin-cli` still does not preserve the directory structure 😕

**Comment by ax2mx** [comment]
Still doesn't.

**Comment by 1sd15** [comment]
Best I've found to fix this is a 4/5 year old extension that might not work. 
ImageMinCLI is a super powerful tool and really amazing! 
It's just a shame it can't preserve folders.
