### ISSUE TITLE
`npm test` currently fails on 'output error on corrupt images'

### ISSUE THREAD

**Issue by benedfit** [imagemin/imagemin#81]
`Uncaught Error: write EPIPE` coming from jpegtran

**Comment by shinnn** [comment]
I ran into the same error on Mac OS X 10.10.2.

```
> imagemin@3.1.0 test /Users/Shinnosuke/github/imagemin
> node test/test.js

  ✔ expose a constructor
  ✔ add a plugin to the middleware stack
  ✔ set source file
  ✔ set destination folder
events.js:76
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at Object.exports._errnoException (util.js:732:11)
    at exports._exceptionWithHostPort (util.js:755:20)
    at WriteWrap.afterWrite (net.js:745:14)
```

Strangely enough, when I replace [the corrupt image](https://github.com/imagemin/imagemin/blob/cb1c5f581b09df756777de8bb53319ee5d7c285c/test/fixtures/test-corrupt.jpg) with [another one](https://github.com/imagemin/imagemin-jpegtran/blob/e74324e81635865f9c0e195a205fdcaabfd8306e/test/fixtures/test-corrupt.jpg), `npm test` passes.

**Comment by shinnn** [comment]
@benedfit I [updated imagemin-jpegtran](https://github.com/imagemin/imagemin-jpegtran/commit/091afcfb9399a307d8344d4b3c69433ccdc12a05) and now `npm test` passes on my environment. Could you reinstall the repo and try `npm test` again?

**Comment by shinnn** [comment]
@benedfit And, I'd like you to tell us your environment.

**Comment by benedfit** [comment]
@shinnn I can confirm that the update to `imagemin-jpegtran` has fix the issue.

For reference my environment is Mac OS X 10.10.1

**Comment by shinnn** [comment]
@benedfit Thanks for reporting :)

**Comment by Iuriy-Budnikov** [comment]
Some time I getting next errror ```events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Error: write EPIPE
  at ChildProcess.<anonymous> (/Users/admin/Projects/markavip/adidas/www/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/index.js:60:11)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1015:16)
  at Socket.<anonymous> (child_process.js:1183:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:485:12)
```

**Comment by shinnn** [comment]
@Iuriy-Budnikov That's not related to this issue. You should read the stack trace carefully.
