### ISSUE TITLE
imagemin sync

### ISSUE THREAD

**Issue by tamtakoe** [imagemin/imagemin#85]
Make please synchronous method for image optimise

```javascript
var optimizedFile.contents = imgmin.runSync(file.contents)
```

It useful when I combined optimize task with other synchronous task
```javascript
file.contents = resize(file.contents);
file.contents = addCopyright(file.contents);
file.contents = imgmin.runSync(file.contents)
```

**Comment by kevva** [comment]
Sorry, not going to happen for now.

**Comment by sindresorhus** [comment]
Nope, it's such a slow progress you should never do that sync as it blocks the event-loops. It's actually not even really possible until 0.12 anyways. And even then we wouldn't do it.

**Comment by sindresorhus** [comment]
Use promises if you want it to look more synchronous.
