### ISSUE TITLE
Global regex test causes inconsistent behavior

### ISSUE THREAD

**Issue by Cauldrath** [imagemin/imagemin#86]
https://github.com/imagemin/imagemin/blob/master/cli.js#L45

This regex shouldn't be global.

**Comment by sindresorhus** [comment]
I agree it shouldn't be global, but I don't see how it would change the behaviour at all?

**Comment by Cauldrath** [comment]
If, for whatever reason, the regex object doesn't get recreated every time this function runs, the test will fail half the time because when doing a test with global regex, it advances past the original match until it reaches the end.

**Comment by sindresorhus** [comment]
> If, for whatever reason, the regex object doesn't get recreated every time this function runs

It's inline so there's no reason. It doesn't.
