### ISSUE TITLE
Add support to compress icon files

### ISSUE THREAD

**Issue by tobiastom** [imagemin/imagemin#88]
I'm not really sure if that is reasonable somehow, but it would be nice to also minimize icon files. As far as I know they are only containers, which can contain almost everything, but I'm not sure.

Whatever they are, reducing their filesize with image in would be pretty cool.

Thanks!

**Comment by kevva** [comment]
This is probably nothing we're going to add for now.

**Comment by tobiastom** [comment]
Of course I accept your decision, but I'd like to know why you made this decision?

Every web project, app, page or whatever has a favicon. That is downloaded a million times and usually it's not compressed or optimized at all. Imagemin seems to be the perfect tool to do the job, as it is already in the workflow of many people to optimize all the other images in their project.

**Comment by kevva** [comment]
Use a png one.

**Comment by tobiastom** [comment]
Which does not support different images for difference sizes.
