### ISSUE TITLE
Invalid option: -strip

### ISSUE THREAD

**Issue by flc** [imagemin/imagemin#89]
hello,

I get the following error on win7 (no error on linux):

```
Unhandled rejection Error: Command failed: Invalid option: -strip

  at ChildProcess.exithandler (child_process.js:658:15)
  at ChildProcess.emit (events.js:98:17)
  at maybeClose (child_process.js:766:16)
  at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

├─┬ gulp-imagemin@2.2.1
│ ├─┬ imagemin@3.1.0
│ │ ├── concat-stream@1.4.7
│ │ ├── get-stdin@3.0.2
│ │ ├── imagemin-gifsicle@4.1.0
│ │ ├── imagemin-optipng@4.2.0
│ │ ├── imagemin-pngquant@4.0.0
│ │ ├── imagemin-svgo@4.1.2
│ │ ├── meow@2.1.0
│ │ ├── optional@0.1.3
│ │ ├── stream-combiner@0.2.1
│ │ ├── through2@0.6.3
│ │ ├── vinyl@0.4.6
│ │ └── vinyl-fs@0.3.13

the only reference to this error I could find is here:
https://github.com/fluffynuts/whisk/blob/master/docs/Instructions.txt#L142

**Comment by shinnn** [comment]
Thanks for reporting.

I want to find the real cause. Could you clone [imagemin-optipng](https://github.com/imagemin/imagemin-optipng) repo to your Windows, run test, and tell use whether it passes or fails?

**Comment by flc** [comment]
hi, sorry for the slow response. 

here is the output running test.js:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Command failed: Invalid option: -strip

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```
probably worth mentioning that during npm install optipng-bin:
```
> optipng-bin@2.0.4 postinstall D:\src\imagemin-optipng\node_modules\optipng-bin
> node lib/install.js

  ‼ The `optipng.exe` binary doesn't seem to work correctly
  ‼ optipng pre-build test failed
  i compiling from source
  × Error: ./configure --with-system-zlib --prefix="D:\src\imagemin-optipng\node_modules\optipng-bin\vendor" --bindir="D:\src\imagemin-optipng\node_modules\optipng-bin\vendor" && make install
Command failed: '.' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
is-png@1.0.0 node_modules\is-png
```

the same on ubuntu:
```
> optipng-bin@2.0.4 postinstall /home/flc/src/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
is-png@1.0.0 node_modules/is-png
```

test.js also passes:
```
  ✔ optimize a PNG

  ✔ 1 test passed
```

**Comment by flc** [comment]
oh, I think a found the problem. I have GnuWin32 installed on windows and it comes with a rather old version of optipng:
```
OptiPNG: PNG optimizer version 0.4.3
```
after downloading the latest from here: http://optipng.sourceforge.net/ and make it the default by manipulating the PATH variable now tests passes and everything seems to work ok.

isn't it possible somehow force to use the optipng.exe that comes with optipng-bin?
https://github.com/imagemin/optipng-bin/tree/master/vendor/win

**Comment by shinnn** [comment]
> isn't it possible somehow force to use the optipng.exe that comes with optipng-bin?

Current `master` branch of optipng-bin does so, but the latest version available on npm doesn't.

OK, we'll release a new version of optipng-bin later.

**Comment by shinnn** [comment]
https://github.com/imagemin/optipng-bin/commit/49fa6b116b4dfb27e4579b13ce81bdd90da5ff3e#commitcomment-10210014

**Comment by shinnn** [comment]
Fixed in https://github.com/imagemin/optipng-bin/commit/d844926f2723cba1bbe7fe353354eeba4f4a43ce. Please reinstall gulp-imagemin.
