### ISSUE TITLE
npm install imagemin fails with "npm ERR! cb() never called!"

### ISSUE THREAD

**Issue by hal-gh** [imagemin/imagemin#90]
Environment:
* OS X 10.9.5 (Darwin macbookpro.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64 x86_64)
* node: v0.10.37
* nvm: 0.24.0
* npm: 2.7.1

Thanks to all the contributors for your hard work with this extremely useful package.

I'm having a lot of problems installing imagemin via npm, where it fails with the error, "npm ERR! cb() never called!".  I have a project that depends on over 50 other packages, and none have this issue.

To troubleshoot this, I have created another, fresh, project, and just instaledl `imagemin-pngquant` followed by `imagemin`, I get the same issue, shown in the output below.

```
myhost:my-project-v01_01 myuser$ node --version
v0.10.37
myhost:my-project-v01_01 myuser$ nvm --version
0.24.0
myhost:my-project-v01_01 myuser$ npm --version
2.7.1

myhost:my-project-v01_01 myuser$ npm install imagemin-pngquant
-
> pngquant-bin@2.0.3 postinstall /path/to/web/my-project-v01_01/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully
imagemin-pngquant@4.0.0 node_modules/imagemin-pngquant
├── is-png@1.0.0
├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
└── pngquant-bin@2.0.3 (logalot@2.1.0, bin-build@2.1.1, bin-wrapper@2.1.3)


myhost:my-project-v01_01 myuser$ npm install imagemin
npm WARN optional dep failed, continuing imagemin-gifsicle@4.1.0
npm WARN optional dep failed, continuing imagemin-jpegtran@4.1.0
npm WARN optional dep failed, continuing imagemin-optipng@4.2.0
npm ERR! cb() never called!
```

**Comment by kevva** [comment]
I'm pretty sure this is an npm issue, although it's strange since you're running a very recent version.

ping @othiym23.

**Comment by hal-gh** [comment]
As usual, my Ubuntu 12.04 system is rock solid. Works as expected:
```
Linux myhost 3.2.0-74-generic #109-Ubuntu SMP Tue Dec 9 16:45:49 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
node 0.10.37
nvm 0.24.0
npm 2.7.1
```

**Comment by shinnn** [comment]
Cannot reproduce the error on these env:

* Mac OS X Yosemite 10.10.2
* npm v2.7.1
* io.js v1.5.1

and,

* Mac OS X Yosemite 10.10.2
* npm v2.7.1
* node v0.10.36

**Comment by kevva** [comment]
Might have something to do with the optional dependencies failing, but it shouldn't report `npm ERR! cb() never called!` because of that.

**Comment by hal-gh** [comment]
I managed to get it working, by matching shinn's environment above (using v0.10.36 instead of .37 solved it)

```
* OS X 10.9.5 (Darwin macbookpro.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64 x86_64)
* node: v0.10.36
* nvm: 0.24.0
* npm: 2.7.1
```

**Comment by hal-gh** [comment]
Apologies - ignore the last message. I have done the same steps again, and I got the error again. I'm going to continue to test this.

**Comment by othiym23** [comment]
FWIW, I can't reproduce this on any of the machines available to me, and there are other issues in @hal-gh's debug logs that lead me to believe there may be something unusual going on in their build environment / npm / node.js setup. The fact that it happens on their OS X host but not an Ubuntu host running the same setup is part of what makes me suspicious, but I can't rule out another race condition within npm (of course) – but I do need a repro case, or logs pointing to the cause of the issue, before I'll have any meaningful idea of what's going on.

**Comment by hal-gh** [comment]
OK, thanks for all the input here. It's very odd that it worked once, but not before or since. I'm stumped. 

I've opened a ticket at [npm/issues/7625](https://github.com/npm/npm/issues/7625), as it seems that it's a more appropriate place for it.

**Comment by hal-gh** [comment]
OK, thanks for all the input here. It's very odd that it worked once, but not before or since. I'm stumped.

**Comment by sryzycki** [comment]
Hey guys,

I stumbled across the same issue (dependencies unmet) today trying to install gulp-imagemin using:
- node v0.10.38
- npm v2.7.3

and the issue went away after locking gulp-image to 1.0.0. Version 1.0.1 and above gave me unmet deps error/warn. Hope that helps!

**Comment by shinnn** [comment]
https://github.com/imagemin/imagemin/issues/90#issuecomment-79616080

> I've opened a ticket at npm/issues/7625, as it seems that it's a more appropriate place for it.

**Comment by hal-gh** [comment]
Just in case anyone else has issues like this, I'm now using the following environment, and it works fine.

```
nvm 0.24.0
node: v0.12.7
npm: 3.3.9
```
