### ISSUE TITLE
Problem with streams?

### ISSUE THREAD

**Issue by tobiastom** [imagemin/imagemin#94]
I'm trying to execute programs through node thought the child process API. Every program I tried did run as expected, with the exception of imagemin. Here's the minimal code that displays my problem:

```
var spawn = require('child_process').spawn;
var process = spawn( 'node_modules/.bin/imagemin', ['Assets/Images/*', 'Public/asset/'], {
	cwd: '/var/folders/xf/_hq9dzv925d_zj_fv06n4jcm0000gn/T/hubot.2RF7YIaK'
} );
process.on( 'close', function( code ) {
	console.log( 'done: ' + code );
} );
```

The directory `Public/asset/` is not created, and no file is being transformed. Using this code on the command line, which should do the same, works as expected:

```
cd /var/folders/xf/_hq9dzv925d_zj_fv06n4jcm0000gn/T/hubot.2RF7YIaK
node_modules/.bin/imagemin Assets/Images/* Public/asset/
```

I did try to fix it by ignoring the `stdin` stream (with `stdio: [ 'ignore', 'pipe', 'pipe' ]` and the files are still not generated, but the script does not run forever. It just ends with return code 0, and nothing happens.

Any idea what might happening here?

Thank you!
Tobias

**Comment by kevva** [comment]
Set `stdio: 'inherit'`.

**Comment by tobiastom** [comment]
Thank you very much @kevva. `inherit` does not really work for me, as I need to have live access to `stderr` and `stdout`. When I use the following code, the raw image data will be in `stdout`:

```
var spawn = require('child_process').spawn;
var process = spawn( 'node_modules/.bin/imagemin', ['Assets/Images/*', 'Public/asset/'], {
	cwd: '/var/folders/xf/_hq9dzv925d_zj_fv06n4jcm0000gn/T/hubot.2RF7YIaK',
	stdio: [ 'ignore', 'pipe', 'pipe' ]
} );
process.on( 'close', function( code ) {
	console.log( 'done: ' + code );
} );
process.stdout.on( 'data', function( data ) {
	console.log( 'data: ' + data );
} );
```

When I execute the command directly inside the terminal there is no output. Background of all this is that I would like to live stream the output of command line calls. Having the raw image data send to a browser is kind of suboptimal.

**Comment by kevva** [comment]
Yeah, it's because of https://github.com/imagemin/imagemin/blob/master/cli.js#L64-L66. @sindresorhus, do you think we should have options for this? I feel like this is an edge case. Would be easier if you'd just use the API.

**Comment by tobiastom** [comment]
Not sure if this is an edge case, but for example a [self hosted CI tool](https://www.phptesting.org) I tried to use had also problems with this. I would assume e.g. Travis CI would have also problems with this, but I don't have a use case to test with them. I'll try to test it somehow.

**Comment by kevva** [comment]
It's an edge case to use CLI tools when there's a programmtic API available.

**Comment by tobiastom** [comment]
Just for the record, travis does not seem to have a problem with this behavior: https://travis-ci.org/tobiastom/imagemin-test#L132-L134

**Comment by kevva** [comment]
I guess it treats that script as `isTTY`. If you're looking in https://github.com/imagemin/imagemin/blob/master/cli.js we're making some assumption depending on if `stdin` and `stdout` are `isTTY`.

**Comment by tobiastom** [comment]
I solved it for me now with [pty.js](https://github.com/chjj/pty.js), which comes with a lot of different kind of problems, but it's working for me.

**Comment by tobiastom** [comment]
@kevva Just for the record, I have the same issue with [pkgrun](https://github.com/reggi/pkgrun), which seems to use the same spawn method.

Here's that I tried with nom scripts:

```
    "imagemin": "pkgrun 'imagemin:*'",
    "imagemin:images": "imagemin Assets/Images/*.* Public/assets/",
    "imagemin:svg": "imagemin Assets/SVG/*.* Build/SVG",
```

The script will never finish the `imagemin:images` task.

**Comment by tobiastom** [comment]
This does not seem to be an edge case for me. I just tried [parallelshell](https://github.com/keithamus/parallelshell) and it has the same problem. 

Here are the scripts to reproduce it:

    "imagemin": "parallelshell 'nom run imagemin:images' 'nom run imagemin:svg'",
    "imagemin:images": "imagemin Assets/Images/*.* Public/assets/",
    "imagemin:svg": "imagemin Assets/SVG/*.* Build/SVG",
