### ISSUE TITLE
Published size

### ISSUE THREAD

**Issue by sindresorhus** [imagemin/imagemin#97]
The size of imagemin with dependencies is really big. The current 3.1.0 clocks in at **126 MB**.

Master is a little better with **50 MB**. @kevva Can we do a new release?

50 MB is still too much though. We should look into how we can improve this.

**Comment by kevva** [comment]
Yup, published `3.2.0` now.

**Comment by franz-josef-kaiser** [comment]
Can this be closed now?

**Comment by sindresorhus** [comment]
@franz-josef-kaiser Has the size improved?

**Comment by franz-josef-kaiser** [comment]
@sindresorhus A `du -hs` (OS X) shows `13M`, so I guess: yes.
